<template>
	<div class="meta" >
	<div class="meta" v-bar ref="vbar">
	<div id="elements-conclusifs" class="view-scroll">
		<h1>Éléments conclusifs</h1>
		<div class="center-col">
			<h3>Vivre le paysage urbain en confinement</h3>
			<p>Durant la p&eacute;riode de confinement &agrave; Montr&eacute;al, la veille informationnelle a r&eacute;v&eacute;l&eacute; l&rsquo;importance et la valorisation de l&rsquo;<em>&eacute;chelle de proximit&eacute;</em> urbaine dans la quotidiennet&eacute; des citoyens (r&eacute;f.{{'\xa0'}}: la rue, le quartier, l&rsquo;&eacute;picerie, etc.) et les enjeux qui lui sont associ&eacute;s. Ainsi, la Ville de Montr&eacute;al propose de nouvelles appropriations de l&rsquo;espace public. Les rues sont cibl&eacute;es pour permettre l&rsquo;installation de terrasses distanc&eacute;es, la d&eacute;ambulation des pi&eacute;tons et le d&eacute;placement s&eacute;curitaire des cyclistes <a class="reference-link" href="https://montreal.ca/articles/les-voies-actives-securitaires-un-plan-de-deplacements-estival" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>. Ces mesures soulignent l&rsquo;&eacute;mergence d&rsquo;une valeur, soit celle de la <em>lenteur</em>. La mobilit&eacute; lente prend corps au sein de la ville, tout comme celle de la <em>solidarit&eacute; sociale et &eacute;conomique</em> puisque les mesures de pi&eacute;tonnisation visent les rues commer&ccedil;antes <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> et promeuvent le march&eacute; local <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Durant cette phase de confinement, plusieurs citoyens montr&eacute;alais ont adopt&eacute; une <em>attitude r&eacute;siliente </em>en regard de l&rsquo;int&eacute;r&ecirc;t manifest&eacute; envers l&rsquo;agriculture urbaine. Les initiatives d&rsquo;am&eacute;nagement de cour arri&egrave;re ou de balcon en espace nourricier <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/577752/la-pandemie-terreau-fertile-pour-les-apprentis-jardiniers" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> t&eacute;moignent d&rsquo;un d&eacute;sir d&rsquo;<em>autonomie alimentaire</em> et/ou d&rsquo;un <em>contact envers la nature</em>.</p>
			<p>Cependant, il a &eacute;t&eacute; relev&eacute; que plusieurs habitations montr&eacute;alaises ne b&eacute;n&eacute;ficiaient pas de balcon, de jardin, d&rsquo;ouverture vers l&rsquo;ext&eacute;rieur, d&rsquo;ensoleillement ou d&rsquo;&eacute;clairage naturel, et que cette situation rendait le confinement particuli&egrave;rement p&eacute;nible pour ses occupants <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1701627/coronavirus-urbanisme-architecture-quoi-ressembleront-villes-apres-pandemie" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>. Les difficult&eacute;s de vivre le confinement au sein d&rsquo;un logement sans contact avec l&rsquo;ext&eacute;rieur font appara&icirc;tre l&rsquo;importance de <em>reconsid&eacute;rer l&rsquo;habitat</em> en milieu urbain afin d&rsquo;offrir un environnement de vie en temps de pand&eacute;mie.</p>
			<p>Par ailleurs, le confinement a r&eacute;v&eacute;l&eacute; l&rsquo;importance des espaces ext&eacute;rieurs publics &agrave; Montr&eacute;al. L&rsquo;achalandage et les usages associ&eacute;s (r&eacute;f.{{'\xa0'}}: pique-nique, d&eacute;tente, sport, etc.) dans les parcs <a class="reference-link" href="https://www.ledevoir.com/societe/578237/le-defi-de-la-distance-dans-les-parcs" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> ont d&eacute;montr&eacute; leur r&ocirc;le essentiel sur le plan de la <em>sociabilit&eacute; </em>et le <em>bien-&ecirc;tre</em> des citoyens. Toutefois, ce contexte pand&eacute;mique aura mis en exergue l&rsquo;absence des parcs publics que les quartiers socialement et &eacute;conomiquement d&eacute;favoris&eacute;s et qui ont &eacute;t&eacute; les plus touch&eacute;s par la COVID-19 <a class="reference-link" href="https://plus.lapresse.ca/screens/ff83c3e0-b983-42ae-9d85-f2de0fbcd024__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>La <em>dignit&eacute; humaine</em> a aussi &eacute;t&eacute; une valeur soulev&eacute;e lors de la crise consid&eacute;rant que l'aide gouvernementale pour l'itin&eacute;rance n'a jamais &eacute;t&eacute; aussi forte, dont 157 millions de dollars canadiens de la part du gouvernement f&eacute;d&eacute;ral <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1691992/hotels-sans-abris-itinerants-covid-toronto-montreal" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> et de nombreuses mesures prises par la Ville de Montr&eacute;al <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32517" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En d&eacute;finitive, l&rsquo;&eacute;chelle de proximit&eacute; urbaine int&egrave;gre l&rsquo;ensemble des enjeux rapport&eacute;s pr&eacute;c&eacute;demment. Lors de cette phase de confinement, elle a r&eacute;v&eacute;l&eacute; la place centrale de l&rsquo;humain dans la ville, soit celle d&rsquo;un humain reclus au destin incertain, mais d&eacute;finitivement r&eacute;solu &agrave; vivre la ville en r&eacute;inventant ses modes de vie en misant sur les potentialit&eacute;s des espaces publics existants et en adoptant une attitude ouverte et empathique.</p>
			<h3>Inclusion urbaine et sociale et mise en perspective</h3>
			<p>D&rsquo;un point de vue prospectif, certaines mesures prises &agrave; Montr&eacute;al pour faire face &agrave; la crise de la COVID-19 sont applicables &agrave; d&rsquo;autres villes poss&eacute;dant des infrastructures urbaines similaires &agrave; Montr&eacute;al. Entre autres, les installations sanitaires (ex.{{'\xa0'}}: halte-r&eacute;pit, centre de jour, centre d&rsquo;h&eacute;bergement d&rsquo;urgence ou annexe d&rsquo;h&ocirc;pital) dans les stationnements ou les parcs publics <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32519&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> et le r&eacute;am&eacute;nagement d&rsquo;&eacute;difices publics d&eacute;sert&eacute;s au c&oelig;ur de la ville <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32581" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> pour venir en aide aux itin&eacute;rants sont des mesures viables et &agrave; pr&eacute;coniser dans d&rsquo;autres contextes urbains. Ces mesures soul&egrave;vent qu&rsquo;il est primordial que les infrastructures urbaines soit compos&eacute;es d&rsquo;espaces publics int&eacute;rieurs et ext&eacute;rieurs au caract&egrave;re libre, adaptable et flexible voir r&eacute;versible pour r&eacute;pondre aux besoins de la population. Ces consid&eacute;rations pourraient favoriser l&rsquo;inclusion sociale en milieu urbain, et ce surtout en temps de crise.</p>
			<p>De plus, la r&eacute;quisition d&rsquo;h&ocirc;tels vides possible en raison de l&rsquo;interruption abrupte du tourisme en temps de pand&eacute;mie <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1691992/hotels-sans-abris-itinerants-covid-toronto-montreal" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> est une solution reproductible &agrave; d&rsquo;autres villes d&eacute;laiss&eacute;es par les touristes pour offrir un refuge ou venir en aide aux centres de soins hospitaliers d&eacute;bord&eacute;s. L&rsquo;inclusion n&rsquo;est pas un enjeu prioritaire dans la planification et la gestion programmatique d&rsquo;un h&ocirc;tel, toutefois certains espaces essentiels au fonctionnement h&ocirc;telier (chambres, toilettes, caf&eacute;t&eacute;rias) r&eacute;pondent &agrave; des besoins primaires lors de pand&eacute;mie et ils ont prouv&eacute; leur pertinence pour suppl&eacute;er &agrave; l&rsquo;absence d&rsquo;infrastructure d&rsquo;accueil &agrave; Montr&eacute;al pour des populations d&eacute;favoris&eacute;es.</p>
			<p>Concernant l&rsquo;am&eacute;nagement urbain, la Ville de Montr&eacute;al a d&eacute;cid&eacute; de cr&eacute;er des &laquo;&thinsp;corridors sanitaires&thinsp;&raquo; pour respecter les mesures de distanciation lors des d&eacute;placements quotidiens de ces citoyens. Ces axes de pi&eacute;tonnisation <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> constituent un nouvel attribut urbain montr&eacute;alais. Cette mesure qui consiste &agrave; offrir plus d&rsquo;espace aux pi&eacute;tons pour circuler de mani&egrave;re distanc&eacute;e au d&eacute;triment de l&rsquo;automobile est relativement simple &agrave; r&eacute;aliser &agrave; moindres co&ucirc;ts et elle pourrait inspirer d&rsquo;autres villes confront&eacute;es &agrave; des probl&egrave;mes de mobilit&eacute; urbaine similaires. Par ailleurs, il est &agrave; souligner que le <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&amp;extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100" target="_blank">Plan estival de la Ville de Montr&eacute;al</a>, qui int&egrave;gre des mesures de pi&eacute;tonnisation de nombreuses rues commerciales et l&rsquo;ajout plusieurs pistes cyclables, <a class="reference-link" href="https://montreal.ca/articles/les-voies-actives-securitaires-un-plan-de-deplacements-estival" target="_blank">Réf{{'\xa0'}}&#x1f855;</a> est une initiative qui a &eacute;t&eacute; prise d&eacute;j&agrave; dans de nombreuses villes &agrave; travers le monde <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1701627/coronavirus-urbanisme-architecture-quoi-ressembleront-villes-apres-pandemie" target="_blank">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Au cours de la veille informationnelle, le th&egrave;me de l&rsquo;inclusion urbaine et sociale a &eacute;t&eacute; tr&egrave;s peu abord&eacute;. En effet, sur 163 articles seulement un d&rsquo;entre eux l&rsquo;aborde mani&egrave;re directe et document&eacute;e. Celui-ci &eacute;voque que les communaut&eacute;s les plus vuln&eacute;rables sont les plus &agrave; risque face &agrave; la crise de la COVID-19. <a class="reference-link" href="https://www.ledevoir.com/societe/577984/aux-confins-des-inegalites" target="_blank">Réf{{'\xa0'}}&#x1f855;</a></p>

			<ChapterNav :previous="true" :next="true" />
		</div>
	</div>
	</div>
	</div>
</template>

<script>
import ChapterNav from '@/components/ChapterNav'

export default {
	name: 'ElementsConclusifs',
	components: {
		ChapterNav
	},
	activated() {
		this.$vuebar.refreshScrollbar(this.$refs.vbar)
	}
}
</script>

<style scoped>
#elements-conclusifs {
	width: 100%;
	height: 100%;
}
</style>