<template>
	<div id="container">
		<h1>Accueil</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium finibus facilisis. Cras magna velit, iaculis sit amet felis quis, sollicitudin pellentesque lorem. Mauris non nulla eu velit consequat consectetur. Curabitur feugiat dui dui, vitae vehicula libero tincidunt non. Mauris rutrum dapibus nibh ut euismod. Cras gravida nisi id sagittis pellentesque. In rutrum est dolor. Maecenas convallis urna fringilla ultrices vestibulum. Sed scelerisque lectus a diam gravida malesuada. Cras vel cursus odio. Duis placerat ut est eget bibendum. Vestibulum dignissim sapien ante, ut ultrices tellus rhoncus luctus.</p>
		<p>Quisque auctor bibendum leo in aliquam. Proin viverra sollicitudin eros, ac malesuada metus interdum eu. Cras euismod, elit sit amet mollis viverra, ipsum ligula fermentum nulla, ut tristique mauris leo sit amet mauris. Curabitur imperdiet est at urna pulvinar, quis dictum tellus volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce cursus luctus dapibus. Vestibulum volutpat rutrum lectus vel tempor. Vivamus ut mauris mi. Ut et lorem tempus, rhoncus enim ut, condimentum justo. Morbi eleifend, enim sed condimentum tristique, dui mauris euismod mi, a blandit dolor arcu ornare nisl. Suspendisse gravida erat at massa bibendum, vel rutrum odio facilisis. Sed eu est non dolor condimentum luctus.</p>
		<h2>Ceci est un titre de deuxième niveau (h2)</h2>
		<p>Ut sed leo fringilla, rutrum ligula id, sodales metus. Morbi eu porttitor nibh. Nunc sed ultricies lectus. Nulla libero quam, elementum vitae mollis in, pretium vitae mi. Quisque non efficitur lacus. Nullam sodales egestas erat ut pellentesque. Maecenas sagittis lacus id commodo faucibus. Suspendisse eu fringilla risus. Morbi et condimentum ante. Nulla aliquet molestie mi, non iaculis sem luctus id. Mauris in finibus eros. Duis eu tincidunt urna. Curabitur finibus lacus orci, eu mattis metus scelerisque non. Nullam eu ornare lectus. Vestibulum non dui odio.</p>
		<p>Duis at consequat nunc. Nunc aliquam, lectus quis condimentum congue, diam ex ultricies augue, vitae fermentum ligula ipsum sed arcu. Mauris pulvinar lorem at viverra porta. Phasellus ante lorem, congue a tincidunt ut, fermentum ac leo. Nam leo ante, consectetur non iaculis in, dapibus eget orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non dapibus nisl. In sagittis malesuada sodales. Pellentesque congue tortor lorem, nec cursus arcu cursus ac. Donec lobortis metus sed eleifend fringilla. Aliquam tellus urna, aliquet a nisl ut, ullamcorper semper orci. Nullam vulputate risus magna, vitae scelerisque eros laoreet quis. Morbi blandit varius ligula ut malesuada. Praesent dolor dui, ullamcorper quis nisl eget, tristique porttitor diam. Integer hendrerit libero quis est mattis fringilla. Sed tristique quam in molestie dignissim.</p>
		<p>Duis imperdiet nibh lectus, vitae egestas urna posuere vitae. Aliquam sollicitudin, ipsum vitae ullamcorper rhoncus, augue tortor consequat lectus, ut lobortis leo ipsum non ipsum. Nunc lacinia porttitor nisi, in blandit tortor. Aenean sit amet neque condimentum, varius massa eu, euismod lacus. Phasellus sagittis ante et tortor egestas, quis fermentum lacus blandit. Proin tincidunt dui ut euismod imperdiet. Etiam dignissim mauris lacus, non vehicula sapien maximus id. Praesent leo arcu, porttitor sit amet sapien posuere, elementum commodo sapien. Etiam sit amet pretium sapien. Sed ornare diam sagittis turpis sollicitudin luctus. Nunc venenatis ac eros a bibendum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras ac mi orci. Vestibulum ac tortor odio.</p>
		<p>Ut hendrerit, risus eu facilisis pharetra, dui sem commodo arcu, fringilla blandit est ipsum et ex. Fusce sollicitudin arcu tellus, id posuere leo lobortis eu. Quisque condimentum neque at dui dignissim, eu lobortis urna consectetur. Nullam maximus pulvinar ligula ac elementum. Nam elementum nunc libero, id pulvinar est condimentum nec. Maecenas eros augue, mattis eu feugiat nec, ullamcorper sed nisl. Mauris sit amet felis id odio dictum accumsan. Nam pulvinar pulvinar quam, a consequat nisi congue sit amet. Quisque pretium ex orci, eu sodales magna dictum quis. Quisque id arcu eget nisi laoreet elementum. Sed tempor ipsum eget enim aliquet, eget blandit diam elementum. Nunc commodo ipsum tellus, eu euismod mi hendrerit ut. Proin hendrerit sapien a elit commodo blandit. Aliquam tempus suscipit ipsum, eu sagittis massa feugiat sit amet. Suspendisse tincidunt eget libero at consequat.</p>
		<p>Donec quis magna eget justo luctus rutrum id a mi. Donec fermentum lorem vitae nulla pulvinar accumsan. Vestibulum finibus dictum mi quis blandit. Nunc dignissim commodo odio at lobortis. Maecenas tincidunt ex ipsum, eget vehicula tellus congue sodales. Suspendisse potenti. Sed lacinia semper quam, eget ornare diam consequat nec. Aliquam lacus libero, ullamcorper id leo vestibulum, ornare egestas diam. Suspendisse accumsan viverra sapien, eget vulputate magna. Vestibulum volutpat luctus nulla et porttitor. Vivamus maximus pretium risus, quis rhoncus mauris consequat quis. Praesent faucibus feugiat eros. Vivamus laoreet ex id ligula consectetur, in fermentum sem dignissim. Quisque velit dui, euismod ut quam rutrum, varius elementum dolor. In suscipit, metus in aliquam tincidunt, leo elit posuere magna, non molestie nisl orci nec orci. Curabitur placerat ipsum erat.</p>
		<p>In vitae feugiat lectus, sed maximus est. Phasellus et ante tristique, tincidunt eros vitae, fringilla diam. Vivamus velit nisi, suscipit non lorem quis, laoreet egestas enim. Fusce erat felis, dictum vitae dolor vel, scelerisque dignissim mi. Aenean nec placerat diam. Sed molestie ultricies ligula, ac auctor ante dictum non. Etiam ac congue elit, ut dapibus orci. Cras et vehicula risus. Curabitur bibendum eu tellus at sollicitudin.</p>
		<p>Pellentesque luctus risus massa, id mattis sapien placerat sed. Etiam sit amet posuere magna. Duis scelerisque, mauris vitae cursus iaculis, nisl arcu pharetra justo, sit amet tempor justo velit ultrices nisl. Quisque in ipsum odio. Nunc finibus lacinia elit, at suscipit lorem aliquet et. Nulla nec justo eget libero ornare faucibus vel quis mi. Nulla mattis, enim et eleifend tristique, tellus neque gravida ipsum, sed ornare nulla nunc ut velit. In hendrerit libero tincidunt nunc placerat consectetur. Duis aliquet vulputate erat accumsan scelerisque. Vivamus laoreet sed ipsum a vehicula. Phasellus dolor arcu, cursus quis pharetra non, rhoncus ut dui.</p>
		<p>Pellentesque nec justo aliquet, tincidunt augue sit amet, porttitor velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam augue turpis, iaculis in augue a, rhoncus scelerisque justo. Sed ullamcorper congue ipsum a posuere. Fusce auctor lectus ut mattis pellentesque. Sed in tristique dui. Sed eu molestie nibh. Cras mattis pharetra nisl, in dignissim odio commodo maximus. Aliquam dictum porta ante, nec varius nisl pharetra in.</p>
		<p>Aliquam volutpat turpis eget urna lacinia rhoncus. Pellentesque rutrum ultricies leo vitae tincidunt. Curabitur augue tortor, efficitur ut euismod dignissim, tempus vel elit. Aenean maximus nisl ut magna gravida aliquet. In hac habitasse platea dictumst. Vestibulum vel vulputate neque. Donec eget diam consectetur elit commodo pretium. Praesent at ipsum id orci gravida rutrum id ut tellus. Praesent sit amet lacinia elit, sit amet lobortis arcu. Quisque semper iaculis arcu, id elementum nibh ultrices et. Integer non tempus purus, vel malesuada sapien. Morbi orci ligula, euismod molestie eleifend non, viverra vel nisl. Morbi dapibus eros at justo semper, eget varius massa suscipit.</p>
		<p>Nam et ligula sit amet est elementum sollicitudin ac vitae neque. Vestibulum in mi porttitor, aliquam sapien nec, lobortis sem. Donec et iaculis magna, porttitor suscipit purus. Quisque egestas sem a ex placerat tempus. Nulla a dui vitae tellus feugiat vulputate vel ac leo. Phasellus a nisi vel leo consectetur convallis. Vivamus semper id sapien quis pharetra. Nam auctor porta ultrices. Curabitur vestibulum imperdiet pulvinar. Ut in sapien eu ligula placerat tincidunt. Mauris venenatis dolor nec diam maximus, sit amet porta ligula consectetur. Aenean dictum iaculis risus, nec placerat felis. Mauris massa nisl, tempus ac ipsum sit amet, semper condimentum erat.</p>
		<p>Nam fringilla quam vel nisi tristique egestas. Aenean quis bibendum quam. Quisque mattis elit ut ex venenatis, ac placerat nulla semper. Ut dapibus justo nibh, vitae ultricies dui tincidunt eu. Quisque sollicitudin porttitor lectus ut vestibulum. Mauris nec est nulla. Sed id quam metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam scelerisque nec metus a fringilla. Aenean pulvinar massa et purus cursus, at fringilla turpis elementum. Duis in libero non lectus finibus venenatis. Ut a est massa.</p>
		<p>Suspendisse consequat, est non lacinia viverra, nisl felis luctus erat, laoreet varius urna dui vel arcu. Maecenas lacus felis, maximus ut neque vel, accumsan interdum libero. Suspendisse convallis auctor condimentum. Nunc tempor interdum facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent at eros nunc. Quisque feugiat nisi sapien. Aenean blandit ex et ex pellentesque, non pharetra ipsum ornare. Suspendisse hendrerit condimentum massa id maximus. Sed dignissim, dolor ac maximus ultricies, turpis felis consectetur magna, quis laoreet augue ipsum quis magna. Mauris ornare, nunc sit amet porta elementum, elit erat efficitur turpis, id malesuada tortor lorem ut risus. Sed fringilla molestie consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean consectetur justo sed bibendum suscipit. Sed elementum sapien quis justo sagittis semper.</p>
		<p>Ut mattis justo vitae erat convallis, eu euismod urna gravida. Duis vehicula metus est, vel cursus ipsum congue et. Vivamus sit amet justo vel libero ultricies mattis. Maecenas sagittis iaculis augue, sit amet blandit odio rhoncus sed. Nullam sem turpis, pellentesque at urna eu, viverra feugiat lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris congue, justo nec viverra condimentum, augue sem ultrices diam, in gravida lorem orci ac libero. Duis vitae sodales massa. Maecenas porta, orci eu hendrerit luctus, diam libero dignissim nisi, in mollis nisi mi in ex. Donec eros nibh, fermentum sit amet ullamcorper ultricies, dignissim ac tellus. Integer non ante nisl. Vestibulum ex massa, luctus eget pulvinar nec, iaculis at orci. Proin in feugiat augue.</p>
	</div>
</template>

<script>
// @ is an alias to /src

export default {
	name: 'Home',
	components: {

	}
}
</script>

<style scoped>
#container {
	width: 100%;
	height: 100%;
	padding: 25px;
}
p {
}
</style>
