<template>
	<div class="meta" >
	<div class="meta" v-bar ref="vbar">
	<div id="mediagraphie" class="view-scroll">
		<h1>Médiagraphie</h1>
		<div class="center-col">
			<h2>Références de presse</h2>
				<h3>Articles de presse</h3>
				<p>Agence QMI. (2020, 5 mai). La COVID-19 fait plus de ravages dans les quartiers à faible revenu. <i>Journal de Montréal</i>. <a class="reference-link" target="_blank" href="https://www.journaldemontreal.com/2020/05/05/la-covid-19-fait-plus-de-ravages-dans-les-quartiers-a-faible-revenu">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Baillargeon, S. (2020, 30 avril). Le virus est implacable avec les plus vulnérables de la société. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/577984/aux-confins-des-inegalites">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Baillargeon, S. (2020, 6 mai). Les images de la lutte contre le coronavirus manquent. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/culture/medias/578374/arret-sur-images?utm_source=infolettre-2020-05-06&amp;utm_medium=email&amp;utm_campaign=infolettre-quotidienne">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Beaudet, G. (2020, 13 mai). L’espace urbain et collectif et les règles de distanciation, selon Gérard Beaudet. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/opinion/idees/578800/sortie-de-crise-urbanisme-l-espace-urbain-et-collectif-et-les-regles-de-distanciation">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Bélair-Cirino, M. et Corriveau, J. (2020, 18 mars). Les refuges pour itinérants sur le qui-vive<i>. Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/575163/coronavirus-les-refuges-pour-itinerants-sur-le-qui-vive">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Bellerose, P. (2020, 29 avril). Des rassemblements extérieurs permis, mais pas encouragés. <i>Journal de Québec</i>. <a class="reference-link" target="_blank" href="https://www.journaldequebec.com/2020/04/29/rassemblements-exterieurs-permis-mais-pas-encourages">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Bérubé, N. (2020, 11 mai). Le Québec en septième place dans le monde. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/f510fc25-89f7-44f3-8e93-a498f2b6f6c4__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Bérubé, N. (2020, 18 avril). Transports : et le silence fut. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202004/17/01-5269905-transports-et-le-silence-fut.php?utm_source=facebook&amp;utm_medium=social&amp;utm_campaign=algofb&amp;fbclid=IwAR1ottDPYphJPJ1US-vJEMEHccBszZG3u6cB0oqvFbTFo9sWllgi6Sf_MQ8">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Boily, D. (2020, 21 avril). Des patients atteints de la COVID-19 logent à l'Hôtel Place Dupuis<i>. ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1696033/coronavirus-place-dupuis-patients-chambres-hotel">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Boily, D. et Gentile, D. (2020, 12 mai). COVID-19 : le CIUSS s’inquiète de la hausse des décès dans Hochelaga-Maisonneuve. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1702044/covid-19-augmentation-deces-homa-inquite-ciusss">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Brisson, B. (2020, 16 mai). Place aux piétons et aux cyclistes. <i>La Presse</i>. <a class="reference-link" target="_blank" href="http://plus.lapresse.ca/screens/515d6d89-7cf2-44fb-aec9-93fbf0a63d73__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Brisson, B. (2020, 29 avril). Montréal prépare l'après-confinement. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/92e5b312-bc91-41af-a136-88b25cddf616__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 11 mai). Place aux vélos!. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/578683/place-aux-velos">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 14 avril). Les atouts de la ville mis à mal par la pandémie. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/576932/faire-de-la-ville-un-havre-du-vivre-ensemble">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 27 avril). La pandémie, terreau fertile pour les apprentis jardiniers. <i>Le Devoir.</i><a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/577752/la-pandemie-terreau-fertile-pour-les-apprentis-jardiniers">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 30 mars). Des vélos qui nous sont essentiels. <i>Le Devoir. </i><a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/576005/des-velos-qui-nous-sont-essentiels">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 4 mai). L’inhabituel silence des avions. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/578203/l-inhabituel-silence-des-avions">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Caillou, A. (2020, 4 mai). Le défi de la distance dans les parcs de Montréal. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/578237/le-defi-de-la-distance-dans-les-parcs">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Carabin, F. (2020, 12 mai). Canicule et pandémie : la Santé publique anticipe des défis. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/actualites/montreal/2445581/canicule-et-pandemie-la-sante-publique-anticipe-des-defis/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Carabin, F. (2020, 29 mars). Marché Jean-Talon : accès restreint aux automobilistes dès jeudi. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/local/rosemont-la-petite-patrie/2442132/marche-jean-talon-acces-restreint-aux-automobilistes-des-jeudi/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cardinal, F. (2020, 15 avril). Le climat : victime de la pandémie (1). <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/be5c8139-7a94-4c7c-be35-9ce53c29e1bb__7C___0.html">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cardinal, F. (2020, 16 avril). Après la COVID-19 reconstruire...en mieux (2). <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/9a5bd941-ce1d-429b-9ea9-45d70d929ee0__7C___0.html">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cardinal, F. (2020, 16 mai). Tous piétons!. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/bcc22c32-aedc-4fb5-972f-1f67e018adf5__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cardinal, F. (2020, 2 mai). Repenser Montréal faire de Montréal une immense terrasse. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/b1b9d8a3-153b-4298-b75e-ff1074ad6327__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cardinal, F. (2020, 5 mai). Les rassemblements sont interdits? Vraiment?. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/edeb48ae-60db-49cf-8067-5c99ccba5e98__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Champagne, S. (2020, 8 mai). Rosemont veut décourager le trafic de transit. <i>La Presse. </i><a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/c475f3bf-ca44-4fe5-93e1-ef38de7e2a2c__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Chouinard, M-A. (2020, 5 mai). Deux mètres au parc. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/opinion/editoriaux/578283/distanciation-physique-deux-metres-au-parc">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Chouinard, T. et Lévesque, K. (2020, 13 mai). Montréal procédera étape par étape. <i>La Presse. </i><a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/d9fe2c58-50f0-4915-aa18-b3f23ddcc747__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Chouinard, T., Krol, A. et Marquis, M. (2020, 29 avril). Un peu d'air pour l'économie. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/d5138171-8e0c-4818-b070-8a0ce056134f__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Codère, J-F. (2020, 15 mai). Montréal rétrécira certaines rues pour l’été. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/ed0eaeba-c84a-4ecc-a875-7caf8ebbf2e3__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Collard, N. (2020, 9 mai). On s’en va au parc?. <i>La Presse.</i><a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/ff83c3e0-b983-42ae-9d85-f2de0fbcd024__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, C. (2020, 7 mai). Parc-Extension risque d’être frappé de plein fouet par la COVID-19. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/578424/inquietude-dans-parc-extension">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. (2020, 14 avril). Peut-on vivre en ville à deux mètres de distance?. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/576952/coronavirus-la-vie-a-deux-metres-de-distance">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. (2020, 28 avril). Montréal-Nord, Saint-Michel et Rivière-des-Prairies sont des "quartiers chauds" de COVID-19 . <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/577870/montreal-nord-saint-michel-et-riviere-des-prairies-sont-des-quartiers-chauds-de-la-pandemie">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. (2020, 29 avril). Un été à réinventer à Montréal. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/577896/un-ete-a-reinventer">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. (2020, 5 mai). La STM installera des panneaux de plexiglas dans ses autobus. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/578339/la-stm-installera-des-panneaux-de-plexiglas-dans-ses-autobus?fbclid=IwAR3t3Xh9keHXt_bEL6CNB1xTmnrurYhKgjxpl9Q43-yqjGSdBKqr1b45-LM">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. (2020, 8 mai). La STM distribuera des masques à ses usagers. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/transports-urbanisme/578594/la-stm-distribuera-des-masques-a-ses-usagers">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. et Fortier, M. (2020, 29 avril). Montréal-Nord en zone rouge. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/577900/montreal-norden-zone-rouge">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Corriveau, J. et Gravel, P. (2020, 30 avril). À quoi ressemblera l'été à Montréal. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/577987/un-ete-sans-fraicheur-ni-trempette">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Cousineau, M-E. (2020, 5 mai). Les aînés révoltés contre les mesures qu'on leur impose. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/578307/la-revolte-des-aines?utm_medium=Social&amp;utm_campaign=Autopost&amp;utm_source=Facebook#Echobox=1588654595">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Denoncourt, J-P. (2020, 12 mai). La clinique de dépistage à Montréal-Nord maintenue jusqu’à jeudi. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/sante/578773/la-clinique-de-depistage-de-la-covid-19-maintenue-jusqu-a-jeudi-au-clsc-montreal-nord">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Derfel, A. (2020, 9 mai). Analysis : Why is the COVID-19 death rate soaring in Hochelaga-Maisonneuve. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/news/local-news/analysis-why-is-the-covid-19-death-rate-soaring-in-hochelaga-maisonneuve/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Desautels, K. (2020, 24 avril). Visite exclusive de l’annexe de l’Hôpital de Verdun. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/actualites/montreal/2440717/annexe-hopital-de-verdun-coronavirus/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Desautels, K. (2020, 6 mai). La rue Wellington devient piétonne pour encourager l’économie locale. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/local/verdun/2444142/la-rue-wellington-devient-pietonne-pour-encourager-leconomie-locale/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Desjardins, F. (2020, 15 avril). Québec invité à accélérer des projets en vue de l'après-crise. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/economie/577007/relance-economique-quebec-invite-a-accelerer-des-projets-en-vue-de-l-apres-crise">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Dubreuil, É. et Schué, R. (2020, 28 avril). COVID-19 : C'est un peu hors de contrôle à Montréal-Nord. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1698270/coronavirus-cas-montreal-nord-quebec-covid-tests">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Dufour, L-M. (2020, 8 mai). L’épicerie de quartier à la rescousse. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/vivre/alimentation/578537/coronavirus-l-epicerie-de-quartier-a-la-rescousse">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Elkouri, R. (2020, 6 mai). Les chants du balcon. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/e2c1dd2c-f191-4084-9a55-32404a23d7f0__7C___0.html?fbclid=IwAR3ZBZ4kosLodSTFIrw3sw8ibcnzNXOinQigBz33Fq4qmK7ZLRIVjwtROO0">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Faucher, O. (2020, 30 avril). Masques gratuits et corridors sanitaires à Montréal-Nord. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/local/montreal-nord/2442201/masques-gratuits-et-corridors-sanitaires-a-montreal-nord/?fbclid=IwAR0MWd8tPgINnPck2iZOnoB9vuVM1gf1mGpWXv-mdPPLfjhDmPblBsa9fhU">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Faucher, O. (2020, 5 mai). Travailler à se rendre malade à Montréal-Nord. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/local/montreal-nord/2443637/travailler-a-se-rendre-malade-a-montreal-nord/?fbclid=IwAR1VgSaKSc7sMjTvm8Hk7LU9xsKEUeTkna6bx4Eyf_s2QvDuWj7gaXgZiCg">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ferah, M. (2020, 4 mai). Forte affluence dans les parcs : la situation est-elle maîtrisée?. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202005/04/01-5272009-forte-affluence-dans-les-parcs-la-situation-est-elle-maitrisee.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ferrandez, L. (2020, 9 avril). Dans la rue, les joggeurs<i>. La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/2b51ad91-dca9-41dd-9518-28967df1d852__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Fleury, E. (2020, 29 avril). Feu vert aux jardins communautaires, à certaines conditions<i>. La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/26a0afa8-70f5-46e4-ad3a-ca15bf861390__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Fournier, V. et Glad, J. (2020, 15 mai). Des rues qui feront école. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/55a99f5b-8591-445a-b27d-9487ecb4db5e__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Gagnon-Paradis, I. (2020, 8 avril). Dire « merci » en couleurs essentielles. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/5292167d-7989-4d1c-a350-00d57596acd3__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Gerbet, T. (2020, 8 avril). Pour isoler les sans-abri, Toronto achète des hôtels et Montréal en réquisitionne. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1691992/hotels-sans-abris-itinerants-covid-toronto-montreal">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Girard, M. (2020, 26 avril). Printemps contre COVID-19. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/ba7e9d62-bb84-4130-8810-0e8ea8021558__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Girard, M. (2020, 9 mai). Ces montréalais que l'on craint. <i>La Presse. </i><a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/cc1765b4-c7ce-45dd-b46c-6fc5e76ff165__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Glad, J. (2020, 11 mai). Ces espaces publics qui sauveront notre été et notre économie locale. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/e272d5e3-26e0-459e-b7a2-4a03fd8b6b5d__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Houdassine, I. (2020, 20 mars). L'ancien hôpital Royal Victoria converti en unité d'isolement pour les sans-abris. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1678832/coronavirus-itinerants-montreal-aide-sans-abri-isolement-covid-19">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ICI-Radio-Canada. (2020, 15 avril). <i>Bixi amorce sa 12e saison à Montréal</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1694064/bixi-debute-saison-abonnements-gratuit-employes-sante">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ICI-Radio-Canada. (2020, 15 avril). <i>COVID-19 : le travail des policiers fait l’objet de nombreuses critiques</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1694424/pandemie-coronavirus-contravention-infraction-distanciation">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ICI-Radio-Canada. (2020, 15 avril). <i>Les professionnels de la construction prêts pour la réouverture des chantiers</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1693975/coronavirus-construction-chantiers-apchq-entrevue">Réf{{'\xa0'}}&#x1f855;</a>.</p>
				<p>ICI-Radio-Canada. (2020, 18 mars). <i>Des artistes de cirque s'exercent au balcon pour la Journée mondiale du cirque</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1695194/artistes-cirque-journee-mondiale-du-cirque-en-piste">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ICI-Radio-Canada. (2020, 2 mai). <i>Trois premières rues piétonnes dans le Plateau-Mont-Royal</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1699520/coronavirus-covid-rues-pietonnes-transport-actif?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ICI-Radio-Canada. (2020, 23 avril). <i>Des messages en 12 langues pour protéger Côte-des-Neiges</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1696789/montreal-cote-neiges-messages-langues-coronavirus">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Joli-Cœur, F-A. (2020, 1<sup>er</sup> avril). Préparer le retour à l’action. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/debats/opinions/202003/31/01-5267355-preparer-le-retour-a-laction.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Jung, D. (2020, 10 mai). À quoi les villes rassembleront-elles après la pandémie?. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1701627/coronavirus-urbanisme-architecture-quoi-ressembleront-villes-apres-pandemie">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Jung, D. (2020, 13 avril). <i>Contracter la COVID-19, moindre souci des itinérants</i>. ICI-Radio-Canada. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1693445/coronavirus-itinerants-sans-abri-montreal-covid-injections-supervisees">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Kramberger, A. (2020, 14 avril). West Island officials and homeowners brace for spring floods. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/news/local-news/west-island-gazette/west-island-officials-and-homeowners-brace-for-spring-floods/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Krol, A. (2020, 4 mai). L'ouverture des commerces reportée d'une semaine à Montréal. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202005/04/01-5272050-louverture-des-commerces-reportee-dune-semaine-a-montreal.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 14 mai). Québec announces a gradual reopening of outdoor sports on May 20. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/sports/quebec-announces-a-gradual-reopening-of-outdoor-sports-on-may-20/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 15 avril). Montréal ouvre des haltes pour offrir un peu de chaleur aux personnes sans-abri. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1694077/montreal-haltes-ouverture-personnes-sans-abri-itinerant-coronavirus">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 17 mars). La COVID-19 rend les sans-abris encore plus vulnérables. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1671967/montreal-covid-19-sans-abri-vulnerable-salubrite-desinfection-prevention">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 19 avril). COVID-19: l’amnistie sera réclamée pour les contraventions. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202004/19/01-5270027-covid-19-lamnistie-sera-reclamee-pour-les-contraventions.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 2 mai). Montréal ferme d’autres stationnements de parcs. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/montreal/578190/montreal-ferme-d-autres-stationnements-de-parcs?utm_medium=Social&amp;utm_campaign=Autopost&amp;utm_source=Facebook#Echobox=1588466291">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>La Presse Canadienne. (2020, 6 avril). Faut-il donner plus d'espace aux piétons pour favoriser la distanciation<i>?. ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1691646/coronavirus-trottoirs-marche-routes-vehicules-confinement?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p><i>La Presse</i>. (2020, 23 avril). <i>Côte-des-Neiges : des messages de prévention diffusés en 12 langues</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/actualites/grand-montreal/2020-04-23/cote-des-neiges-des-messages-de-prevention-diffuses-en-12-langues">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Labbé, J. (2020, 14 avril). La mairesse Plante prépare un plan de relance pour le Montréal postpandémie. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1693999/causerie-ccmm-leblanc-coronavirus-covid-19-etat-urgence-bixi?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lagacé, P. (2020, 12 mai). Montréal-Nord, un beau décor. <i>La Presse.</i><a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202005/12/01-5273173-montreal-nord-un-beau-decor.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lalonde, M. (2020, 11 mai). Back to work for Quebec’s construction industry on Monday. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/news/local-news/back-to-work-for-quebecs-construction-industry-on-monday/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lalonde, M. (2020, 15 avril). Gardeners rejoice as nurseries and garden centres allowed to reopen. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/news/local-news/gardeners-rejoice-as-nurseries-and-garden-centres-allowed-to-reopen/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lepage, G. (2020, 30 avril). L'été prend ses quartiers au marché Jean-Talon. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/consommation/577981/l-ete-prend-ses-quartiers-au-marche-jean-talon">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lévesque, F. et Mazataud, V. (2020, 7 avril). Merci sur tous les murs de la ville. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/culture/arts-visuels/576539/merci-sur-tous-les-murs-de-la-ville">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lévesque, K. (2020, 13 mai). Le plan estival d’aménagement urbain de Montréal dévoilé vendredi. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202005/13/01-5273367-le-plan-estival-damenagement-urbain-de-montreal-devoile-vendredi.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Lévesque, K. (2020, 29 avril). Montréal prépare un «plan estival» de déconfinement. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202004/29/01-5271374-montreal-prepare-un-plan-estival-de-deconfinement.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Loriggio, P. (2020, 8 mai). COVID-19 : qu’en sera-t-il des comportements à long terme. <i>La Presse.</i><a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202005/08/01-5272839-covid-19-quen-sera-t-il-des-comportements-a-long-terme-.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Magalhaes, Z. (2020, 14 mai). Une pétition demande la réouverture « immédiate » du Jardin Botanique. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/uncategorized/2445934/une-petition-demande-la-reouverture-immediate-du-jardin-botanique/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Magalhaes, Z. (2020, 7 mai). Des « superblocs » pour donner la priorité aux piétons de Rosemont. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/uncategorized/2444429/des-superblocs-pour-donner-la-priorite-aux-pietons-de-rosemont-la-petite-patrie/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Mazataud, V. (2020, 1<sup>er</sup> mai). Montréal-Nord, côté solidarité<i>. Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/578139/montreal-nord-cote-solidarite">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>McEvoy, J. et Schué, R. (2020, 15 avril). Réouverture des écoles : les profs et les directeurs dans le néant.<i> ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1694007/ecole-virus-ouverture-cpe-quebec-coronavirus-deconfinement">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Monpetit, C. (2020, 7 mai). Le toucher, ce besoin à redéfinir<i>. Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/culture/578444/sociologie-redessiner-la-vie-au-bout-des-doigts">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Morissette, N. (2020, 24 avril). Quel avenir pour les terrasses à Montréal ?. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/29aa14be-d20a-4ee3-8c90-f08545f6f572__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Nadeau, J. (2020, 4 mai). Immersion dans la vie nocturne de Montréal pendant la pandémie. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/578233/montreal-la-nuit">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ouellette Vézina, H. (2020, 15 mai). Plusieurs axes « réaménagés » pour les piétons et les cyclistes à Montréal. <i>Journal Métro</i>. <a class="reference-link" target="_blank" href="https://journalmetro.com/actualites/montreal/2446277/plusieurs-axes-reamenages-pour-les-pietons-et-les-cyclistes-a-montreal/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Perreault, L-J. (2020, 3 avril). Ouvrons les rues aux piétons. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/af46b3e2-8ff4-4c87-a743-6bcd9e8773d3__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Pratt, A. (2020, 1<sup>er</sup> mai). Changerons-nous vraiment?. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/7a745908-a14e-44a6-8aa8-2d4b8c7c4a89__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Renaud, P. (2020, 26 mars). Isolement | Journal de route en temps de pandémie. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/575730/isolement-journal-de-route-en-temps-de-pandemie">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Roy-Brunet, B. (2020, 7 mai). Hochelaga-Maisonneuve : Bonheur mobile pour égayer les ruelles. <i>Journal de Montréal</i>. <a class="reference-link" target="_blank" href="https://www.journaldemontreal.com/2020/05/07/hochelaga-maisonneuve--bonheur-mobile-pour-egayer-les-ruelles">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Rozenn, N. (2020, 11 mai). Transport en commun : impossible de respecter la distanciation physique, selon les experts. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1701725/ctt-stm-transports-covid19-distanciation-impossible-deconfinement">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Savard, C. (2020, 26 avril). Changeons nos villes pour le mieux. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/6c11e4da-c3e5-4507-af99-a2133c7e00b4__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Schué, R. (2020, 23 avril). Des distributeurs de gel désinfectant installés dans le métro. <i>ICI-Radio-Canada</i>. <a class="reference-link" target="_blank" href="https://ici.radio-canada.ca/nouvelle/1696828/distributeurs-gel-desinfectants-metro-montreal-covid-19">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Siag, J. (2020, 9 mai). Alfonse sème le bonheur dans les ruelles. <i>La Presse. </i><a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/127ee4dd-7035-4322-9e7b-988f5b550eb8__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Sioui, M-M. (2020, 8 mai). La grande région de Montréal fermée jusqu’au 25 mai. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/578574/fermee-jusqu-au-25-mai">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Sioui, M-M. (2020, 8 mai). Retour en classe au secondaire pour élèves handicapées seulement. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/societe/education/578576/retour-en-classe-au-secondaire-pour-eleves-handicapes-seulement">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Sirois, A. (2020, 1<sup>er</sup> mai). Ils se battent avec une armure trouée. <i>La Presse</i>. <a class="reference-link" target="_blank" href="https://plus.lapresse.ca/screens/bcfef450-1b54-452e-bd28-c12653ae7070__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Thibault, E. (2020, 17 mars). COVID-19: des pouvoirs accrus pour les policiers?.<i> Journal de Montréal</i>. <a class="reference-link" target="_blank" href="https://www.journaldemontreal.com/2020/03/17/covid-19-des-pouvoirs-accrus-pour-les-policiers">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Tomesco, F. (2020, 14 avril). Montreal to decide on new 'health corridors' by week's end: Plateau mayor. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/business/local-business/montreal-to-decide-on-new-health-corridors-by-weeks-end-plateau-mayor/">Réf{{'\xa0'}}&#x1f855;</a>.</p>
				<p>Tomesco, F. (2020, 7 avril). Notre-Dame-des-Neiges cemetery closed until further notice. <i>Montreal Gazette</i>. <a class="reference-link" target="_blank" href="https://montrealgazette.com/news/local-news/notre-dame-des-neiges-cemetery-closed-until-further-notice/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Valiante, G. (2020, 15 avril). Le rôle nouveau des policiers inquiète des experts. <i>La</i><i>Presse</i>. <a class="reference-link" target="_blank" href="https://www.lapresse.ca/covid-19/202004/15/01-5269506-le-role-nouveau-des-policiers-inquiete-des-experts.php">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Wysocka, N. (2020, 11 avril). L'annulation des grands événements prolongée jusqu'au 31 août. <i>Le Devoir</i>. <a class="reference-link" target="_blank" href="https://www.ledevoir.com/politique/quebec/576846/un-ete-sans-culture-ni-sport-a-quebec">Réf{{'\xa0'}}&#x1f855;</a></p>
				<h3>Communiqués de presse</h3>
				<p>CNW Telbec. (2020, 13 avril). <i>Guide COVID-19 : de nouvelles mesures pour assurer la santé sur les chantiers de construction</i>. <a class="reference-link" target="_blank" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?Page=2&amp;idArticle=2804138675">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>CNW Telbec. (2020, 13 mars). <i>Pandémie de COVID-19 - Le gouvernement du Québec annonce la fermeture des écoles, des cégeps, des universités et des services de garde</i>. <a class="reference-link" target="_blank" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?Page=8&amp;TaillePage=50&amp;idArticle=2803137507">Réf{{'\xa0'}}&#x1f855;</a>.</p>
				<p>CNW Telbec. (2020, 15 avril). <i>Contraventions à des jeunes en situation d'itinérance : comment s'isoler quand on vit dans la rue?.</i><a class="reference-link" target="_blank" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?idArticle=2804150115">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 11 mai). <i>Des mesures pour les piétons et les familles : piétonnisations sur Sainte-Catherine et Nouvelles rues familiales et actives. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 11 mai). <i>J'achète local dans MHM : 230 % de l'objectif atteint en 48 heures!. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32650">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 13 mars). <i>Espace pour la vie ferme ses musées à compter du 13 mars</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32470&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 14 mai ). <i>MHM est présent sur le terrain : intensification des mesures</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32658">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 14 mai). <i>LaSalle combat le COVID-19. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32655">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 15 mai). <i>Les voies actives sécuritaires : un plan de déplacements estival</i>. <a class="reference-link" target="_blank" href="https://montreal.ca/articles/les-voies-actives-securitaires-un-plan-de-deplacements-estival">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 16 avril). <i>La Ville appuie la réalisation d'un projet de logement social pour les personnes en situation d'itinérance. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32569">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 19 mars). <i>Le Sud-Ouest s'attaque aux évictions abusives</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32480&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 2 mai).COVID-19 Montréal ferme les stationnements de certains grands parcs pour favoriser le maintien de la distanciation physique<i>. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32612&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 20 avril). <i>La Ville de Montréal déploie une nouvelle série de mesures pour soutenir les personnes en situation d'itinérance</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32581">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 22 mars). <i>COVID-19 - Montréal ferme les modules et aires de jeu</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32483&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 23 mars). <i>COVID-19 - Montréal annonce des changements à ses activités de stationnement</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32485&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 24 avril). <i>COVID 19 - LaSalle prête son aréna pour la mise en place d'un hôpital de campagne.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32590">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 28 mars). <i>COVID-19 - Montréal annonce la fermeture des parcs canins.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32509&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 29 avril). <i>Covid-19 : L'arrondissement de Montréal-Nord déploie une série de mesures.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32602">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 3 mai). <i>Un effort collectif dans Montréal-Nord pour la distribution de masques de protection.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32614">Réf{{'\xa0'}}&#x1f855;</a>.</p>
				<p>Ville de Montréal. (2020, 30 avril). <i>Ouverture des jardins communautaires : la Ville de Montréal annonce plusieurs mesures pour améliorer la sécurité alimentaire.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32604">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 30 avril). <i>Ouverture des marchés saisonniers et mesures préventives dans les marchées publics.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32605">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 31 mars). <i>La Ville de Montréal, en collaboration avec l'arrondissement de MHM, met en place un 5e centre de jour pour les sans-abri dans le quartier de Hochelaga</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32519&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 4 mai). <i>Soutien à l’achat local | Livraison à vélo maintenant disponible dans VSP.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32618&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 5 avril). <i>COVID-19 Montréal ferme les stationnements du parc du Mont-Royal et l'île Notre-Dame. </i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32527&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 5 mai). <i>Trois mesures réglementaires additionnelles pour limiter la pénurie de logements.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32621&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 6 mai). <i>Déclaration sur la piétonnisation de la rue Wellington. </i><a class="reference-link" target="_blank" href="https://montreal.ca/actualites/declaration-sur-la-pietonnisation-de-la-rue-wellington">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 7 mai). <i>Rues locales : des mesures novatrices pour les piétons et les familles!. </i><a class="reference-link" target="_blank" href="https://montreal.ca/actualites/rues-locales-des-mesures-novatrices-pour-les-pietons-et-les-familles?fbclid=IwAR3KEtEAFeI07GujqoSYJn7QWPNOQJUv4g7NVgoB2VNvzSBuAAzwZHSji54">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 9 avril). <i>COVID-19: Montréal lance un appel de propositions de 1 M$ destiné aux OBNL</i>. <a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32550&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ville de Montréal. (2020, 9 mai). <i>La distribution d’équipement de protection contre la Covid-19 se poursuit à Montréal-Nord.</i><a class="reference-link" target="_blank" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32646&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a></p>
				<h3>Plateformes web d’organismes à but non lucratif (OBNL)</h3>
				<p>ASFQ. (2020, 10 mai). Soutien technique pour l’adaptation anti-COVID des petits commerces et organismes. <a class="reference-link" target="_blank" href="https://www.asf-quebec.org/soutien-technique-anti-covid-pour-petits-commerces-et-organismes/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>ASFQ. (2020, 21 avril). Appel à bénévoles - aménagements d'urgence COVID-19. <a class="reference-link" target="_blank" href="https://www.asf-quebec.org/appel-a-benevoles-amenagements-durgence-covid19/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Héritage Montréal. (2020, 16 mars). Infolettre Héritage Montréal. <a class="reference-link" target="_blank" href="http://link.logilys.com/v/443/2f00c9aeda201034343fd8288c4bc73c53fcb9a97447a6a7">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Ordre des architectes du Québec. (2020, 27 mars<i>). Publication du "Guide de survie à l'intention de la communauté architecturale"</i>. <a class="reference-link" target="_blank" href="https://www.oaq.com/covid-19-guide-de-survie/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<h3>Magazines en ligne</h3>
				<p>Bonin, M., Gagnon, E. et Moro-Lin, P. (2020, 24 avril). MANIFESTE| Reconstruire doucement | Partie 1 : Vers une ville transitoire. <i>Kollectif</i>. <a class="reference-link" target="_blank" href="http://kollectif.net/manifeste-reconstruire-doucement/?utm_medium=email&amp;utm_campaign=Bulletin%2020200424&amp;utm_content=Bulletin%2020200424%20CID_5090aeb95b20dcd08027d24d897e71ea&amp;utm_source=Campaign%20Monitor&amp;utm_term=Publications%20Le%20Comit%20%20MANIFESTE%20%20Reconstruire%20doucement%20%20Partie%201%20%20Vers%20une%20ville%20transitoire&amp;fbclid=IwAR1LgIJKhdEPKF2r93AjyFY4filDUyLT1c8e34Xo_imFuq5p3OBA5__sK28">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Chiasson, É. (2020, 28 avril). Agriculture urbaine: aménager un potager chez soi. <i>Index Design.</i><a class="reference-link" target="_blank" href="https://www.index-design.ca/article/agriculture-urbaine-amenager-un-potager-chez-soi?nl">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Heintz, S. (2020, 27 avril). L'échelle humaine requiert des espaces de socialisation et de détente vastes. <i>Index Design</i>. <a class="reference-link" target="_blank" href="https://www.index-design.ca/article/l-echelle-humaine-requiert-des-espaces-de-socialisation-et-de-detente-vastes?nl">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Kollectif. (2020, 17 avril). COVID-19 | Construction résidentielle : réouverture de certains chantiers à compter du 20 avril. <a class="reference-link" target="_blank" href="http://kollectif.net/covid-19/">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Paulhiac Scherrer, F. (2020, 4 mai). Circuler à Montréal tout en étant "distancié"?. <i>L’actualité</i>. <a class="reference-link" target="_blank" href="https://lactualite.com/societe/circuler-a-montreal-tout-en-etant-distancie/?utm_source=L%E2%80%99actualit%C3%A9&amp;utm_campaign=c5f20acca3-EMAIL_CAMPAIGN_2020_05_05_01_09&amp;utm_medium=email&amp;utm_term=0_f566f03091-c5f20acca3-397197122">Réf{{'\xa0'}}&#x1f855;</a></p>
				<p>Stréliski, L. (2020, 29 avril). La promesse timide du printemps. <i>L’actualité</i>. <a class="reference-link" target="_blank" href="https://lactualite.com/societe/la-promesse-timide-du-printemps/?utm_campaign=daily&amp;utm_source=newsletter&amp;utm_medium=email&amp;utm_content=article2_button&amp;utm_term=La%2Bpromesse%2Btimide%2Bdu%2Bprintemps">Réf{{'\xa0'}}&#x1f855;</a></p>
			<h2>Index des photographies</h2>
			<h2>Références scientifiques</h2>
		</div>
		<div class="center-col">
			<ChapterNav :previous="true" :next="false" />
		</div>
	</div>
	</div>
	</div>
</template>

<script>
import ChapterNav from '@/components/ChapterNav'

export default {
	name: 'Mediagraphie',
	components: {
		ChapterNav
	},
	activated() {
		this.$vuebar.refreshScrollbar(this.$refs.vbar)
	}
}
</script>

<style scoped>
#mediagraphie {
	width: 100%;
	height: 100%;
}
</style>