<template>
	<div class="meta" >
	<div class="meta" v-bar ref="vbar">
	<div id="questionnements" class="view-scroll">
		<h1>Questionnements en quête de réponses</h1>
		<div class="center-col">
			<p>Les questionnements portés par la Chaire UNESCO en paysage urbain en temps de confinement en raison de la COVID-19 à Montréal se divisent en cinq thèmes, soient l’<em>aménagement</em>, l’<em>économie</em>, le <em>mode de vie</em>, l’<em>inclusion</em> et la <em>résilience</em>. Au sein de ces cinq thèmes, les <em>dimensions sociales</em>, <em>culturelles</em> et <em>environnementales</em> sont abordées de manière transversale.</p>


			<h2>Aménagement / <br/><em>confinement</em></h2>
			
			<h3>Quels sont les mesures et les outils mis en œuvre à Montréal concernant l’aménagement des espaces publics {{'\xa0'}}?</h3>
			<p>Au d&eacute;but du confinement, la place des Festivals s&rsquo;est vue h&eacute;berger temporairement, du 23{{'\xa0'}}mars 2020 au 20{{'\xa0'}}avril 2020, une clinique de d&eacute;pistage en attendant que les infrastructures montr&eacute;alaises puissent s&rsquo;adapter et r&eacute;pondre aux demandes de la population <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-04-20/la-clinique-covid-demantelee-au-centre-ville-de-montreal">Réf{{'\xa0'}}&#x1f855;</a>. De plus, des installations dans les parcs et stationnements publics &agrave; travers Montr&eacute;al accueillent des extensions d&rsquo;h&ocirc;pitaux <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32590">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="https://ciusss-centresudmtl.gouv.qc.ca/actualite/covid-19-ouverture-prochaine-dune-annexe-lhopital-de-verdun">Réf{{'\xa0'}}&#x1f855;</a> et les itin&eacute;rants pour r&eacute;pondre &agrave; leur besoin sanitaire <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32517">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Concernant l&rsquo;espace public &agrave; Montr&eacute;al, le gouvernement québécois a prescrit une distanciation de deux mètres entre chaque individu de différents ménages. Les citadins &eacute;prouvaient de la difficult&eacute; &agrave; respecter ces mesures lorsqu&rsquo;ils effectuent leurs achats essentiels sur les rues commer&ccedil;antes. Pour s&rsquo;assurer du respect de cette mesure, la Ville de Montr&eacute;al a d&rsquo;abord mis en place des corridors sanitaires sur l&rsquo;avenue Mont-Royal au Plateau Mont-Royal <a class="reference-link" href="https://montrealgazette.com/business/local-business/montreal-to-decide-on-new-health-corridors-by-weeks-end-plateau-mayor/">Réf{{'\xa0'}}&#x1f855;</a>. Les corridors sanitaires consistent &agrave; retirer les deux all&eacute;es de stationnement en bordure des avenues commer&ccedil;antes, ainsi la Ville de Montr&eacute;al offre un espace pi&eacute;tonnier &eacute;largi aux citoyens permettant une distanciation efficace <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>. Il est int&eacute;ressant de noter que les corridors sanitaires repr&eacute;sentent une mesure qui affecte directement l&rsquo;am&eacute;nagement de l&rsquo;espace public. De plus, elle s&rsquo;est multipli&eacute;e rapidement dans les arrondissements de Montr&eacute;al, tels{{'\xa0'}}Ahuntsic-Cartierville, Le Plateau-Mont-Royal, C&ocirc;te-Des-Neiges-Notre-Dame-De-Gr&acirc;ce, Outremont, Rosemont-La-Petite-Patrie, Mercier&ndash;Hochelaga-Maisonneuve, Verdun, Ville-Marie et le Sud-Ouest <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32575">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>De m&ecirc;me, l&rsquo;arrondissement Rosemont-La-Petite-Patrie s&rsquo;est inspir&eacute; du concept catalan des superblocks en divisant son arrondissement en diff&eacute;rents secteurs et en d&eacute;terminant des rues avec circulation de transit automobile permise, alors que d&rsquo;autres sont r&eacute;serv&eacute;es seulement &agrave; la circulation automobile lente et locale. En amont, cet arrondissement a ajouté 50 km &agrave; son r&eacute;seau de pistes cyclables <a class="reference-link" href="https://plus.lapresse.ca/screens/c475f3bf-ca44-4fe5-93e1-ef38de7e2a2c__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. Similairement, la Ville de Montr&eacute;al a proposé de r&eacute;server plusieurs rues commer&ccedil;antes &agrave; Montr&eacute;al seulement aux pi&eacute;tons lors du d&eacute;voilement de son <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100">plan estival</a> <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-05-13/le-plan-estival-d-amenagement-urbain-de-montreal-devoile-vendredi">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Sur le plan du transport, la soci&eacute;t&eacute; des transports de Montr&eacute;al (STM) a distribué du gel d&eacute;sinfectant &agrave; l&rsquo;int&eacute;rieur des stations de m&eacute;tro <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1696828/distributeurs-gel-desinfectants-metro-montreal-covid-19">Réf{{'\xa0'}}&#x1f855;</a>. De plus, des ing&eacute;nieurs de la firme <i>Intervia</i> ont d&eacute;veloppé une application pour permettre de pr&eacute;venir les utilisateurs de la STM de l’achalandage dans les autobus <a class="reference-link" href="https://plus.lapresse.ca/screens/92e5b312-bc91-41af-a136-88b25cddf616__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. Malgr&eacute; ses efforts, la STM soul&egrave;ve que les mesures de distanciation ne peuvent &ecirc;tre respect&eacute;es dans son r&eacute;seau en d&eacute;montrant qu&rsquo;avec un maximum de 15 personnes par bus et de 150 par m&eacute;tro, la demande s&rsquo;&eacute;l&egrave;verait &agrave; 8 000 bus et 800 rames de m&eacute;tro, alors que la STM ne poss&egrave;de seulement 1 425 bus et 97 rames de m&eacute;tro <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1701725/ctt-stm-transports-covid19-distanciation-impossible-deconfinement">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Aux yeux des m&eacute;dias, la reconsid&eacute;ration que la Ville de Montr&eacute;al effectue au sujet de l'espace public d&eacute;di&eacute; aux pi&eacute;tons et aux cyclistes pourrait mener &agrave; un d&eacute;couragement de l'utilisation automobile tout en encourageant une mobilit&eacute; &eacute;cologique <a class="reference-link" href="https://plus.lapresse.ca/screens/92e5b312-bc91-41af-a136-88b25cddf616__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			
			<h3>Quelles sont les directives émises par les autorités gouvernementales et municipales pour utiliser les espaces publics, les espaces collectifs, etc.{{'\xa0'}}?</h3>
			<p>En date du 11{{'\xa0'}}avril 2020, le gouvernement qu&eacute;b&eacute;cois, appuy&eacute; par la Ville de Montr&eacute;al, a forcé l'annulation de tout &eacute;v&egrave;nement public pour l&rsquo;&eacute;t&eacute; 2020. Les espaces publics collectifs, telles l'&icirc;le Notre-Dame et sa place des festivals, ne seront donc pas &agrave; disposition des citoyens cette ann&eacute;e <a class="reference-link" href="https://www.ledevoir.com/politique/quebec/576846/un-ete-sans-culture-ni-sport-a-quebec">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}} &Eacute;galement, la Ville de Montr&eacute;al a annoncé la fermeture des modules de jeu pour enfants le 22{{'\xa0'}}mars 2020 <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32483&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a> et les parcs canins le 28{{'\xa0'}}mars 2020 <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32509&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a> pour freiner la contagion de la COVID-19.</p>
			<p>Concernant les parcs, la Ville de Montr&eacute;al a incité ses citoyens &agrave; visiter uniquement ceux &agrave; proximit&eacute; de leur milieu de vie et a fermé les stationnements dans les parcs pour &eacute;viter les d&eacute;placements dans diff&eacute;rents arrondissements <a class="reference-link" href="https://www.ledevoir.com/politique/montreal/578190/montreal-ferme-d-autres-stationnements-de-parcs?utm_medium=Social&amp;utm_campaign=Autopost&amp;utm_source=Facebook#Echobox=1588466291">Réf{{'\xa0'}}&#x1f855;</a>. Les directives des autorit&eacute;s indiquent qu'il est interdit de se rassembler dans les parcs, cependant selon les d&eacute;crets, si chaque individu de diff&eacute;rents m&eacute;nages se tenait &agrave; deux m&egrave;tres de distance, ils ne pouvaient en aucun cas recevoir une contravention <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-05-04/forte-affluence-dans-les-parcs-la-situation-est-elle-maitrisee">Réf{{'\xa0'}}&#x1f855;</a>. Similairement, les jardins communautaires et les p&eacute;pini&egrave;res, en raison de la demande citoyenne, ont été consid&eacute;r&eacute;s comme des services essentiels <a class="reference-link" href="https://montrealgazette.com/news/local-news/gardeners-rejoice-as-nurseries-and-garden-centres-allowed-to-reopen/">Réf{{'\xa0'}}&#x1f855;</a>. &Agrave; ce sujet, les directives des autorit&eacute;s demandaient de respecter la distanciation de deux m&egrave;tres en suivant un horaire pr&eacute;cis sans partager ses outils et de nettoyer fr&eacute;quemment les espaces communs <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32604">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Pour les espaces collectifs int&eacute;rieurs publics, tels les centres communautaires, les lieux culturels, biblioth&egrave;ques, piscines, ar&eacute;nas, installations sportives et chalets dans les parcs aucune directive d&rsquo;utilisation n&rsquo;a été donn&eacute;e, car ils sont demeurés ferm&eacute;s <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32509&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Pour le transport en commun, la Soci&eacute;t&eacute; des Transports de Montr&eacute;al (STM) a recommandé fortement le port du masque pour les usagers de son r&eacute;seau, cependant elle ne pouvait l&rsquo;obliger <a class="reference-link" href="https://www.ledevoir.com/politique/montreal/578339/la-stm-installera-des-panneaux-de-plexiglas-dans-ses-autobus?fbclid=IwAR3t3Xh9keHXt_bEL6CNB1xTmnrurYhKgjxpl9Q43-yqjGSdBKqr1b45-LM">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			
			<h3>La période de confinement engendre-t-elle une valorisation du paysage urbain auprès des Montréalais{{'\xa0'}}?</h3>
			<p>Suite au confinement, les Montréalais semblent vouloir profiter de l’extérieur en été. De ce fait, la Ville de Montréal a préparé un plan qui permettra aux citadins de profiter de leur paysage urbain tout en respectant les mesures sanitaires <a class="reference-link" href="https://www.ledevoir.com/politique/montreal/577896/un-ete-a-reinventer">Réf{{'\xa0'}}&#x1f855;</a>. De plus, il est soulev&eacute; dans les m&eacute;dias qu&rsquo;il est difficile pour la sant&eacute; mentale des Qu&eacute;b&eacute;cois de rester constamment &agrave; l&rsquo;int&eacute;rieur <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>, donc le <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100">plan estival</a> de pi&eacute;tonnisation des rues est une revalorisation de la ville pour donner la chance &agrave; tous de sortir s&eacute;curitairement. De plus, de nombreux Montr&eacute;alais se sont plaints en d&eacute;but de confinement concernant la fermeture des r&eacute;parateurs de v&eacute;lo, ceux-ci n&rsquo;&eacute;tant pas consid&eacute;r&eacute;s essentiels <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/576005/des-velos-qui-nous-sont-essentiels">Réf{{'\xa0'}}&#x1f855;</a>. Cette plainte t&eacute;moigne de l&rsquo;int&eacute;r&ecirc;t des citadins envers les sorties &agrave; v&eacute;lo &agrave; Montr&eacute;al pour explorer le paysage urbain.</p>
			<p>En amont, d&egrave;s le retour du beau temps les autorit&eacute;s et les m&eacute;dias ont remarqu&eacute; une forte affluence dans les parcs <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-05-04/forte-affluence-dans-les-parcs-la-situation-est-elle-maitrisee">Réf{{'\xa0'}}&#x1f855;</a> et un achalandage de promeneurs dans les rues <a class="reference-link" href="https://plus.lapresse.ca/screens/29aa14be-d20a-4ee3-8c90-f08545f6f572__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a> qui t&eacute;moignent de la valorisation des citoyens envers leur ville. De plus, les experts en design urbain et les r&eacute;sidents ont r&eacute;alisé l&rsquo;importance d&rsquo;espaces publics vastes dans le paysage urbain, d&rsquo;autant plus que celui-ci est manquant dans certains quartiers <a class="reference-link" href="https://plus.lapresse.ca/screens/ff83c3e0-b983-42ae-9d85-f2de0fbcd024__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En d&eacute;but de confinement, pour revaloriser la ville devenue d&eacute;serte et remercier les travailleurs essentiels le collectif  <a class="reference-link" href="https://www.paperole.com/"><i>Paperole</i></a> a r&eacute;uni un groupe cr&eacute;atif pour cr&eacute;er des murales d&rsquo;affiches color&eacute;es &agrave; travers la ville <a class="reference-link" href="https://www.ledevoir.com/culture/arts-visuels/576539/merci-sur-tous-les-murs-de-la-ville">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			
			<h3>Suite au confinement montréalais, peut-on espérer la mise en œuvre d’initiatives en design urbain{{'\xa0'}}?</h3>
			<p>Le <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&amp;extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100"><i>Plan estival de la Ville de Montr&eacute;al</i></a> encourage l’activité piétonne et cycliste au détriment de la voiture <a class="reference-link" href="https://montreal.ca/actualites/plan-estival-de-corridors-de-transports-actifs-du-plateau-mont-royal#:~:text=Plan%20estival%20de%20corridors%20de%20transports%20actifs%20du%20Plateau%2DMont%2DRoyal,-Publi%C3%A9%20le%2015&amp;text=Dans%20la%20foul%C3%A9e%20de%20l,des%20pi%C3%A9tons%20et%20des%20cyclistes.">Réf{{'\xa0'}}&#x1f855;</a>. Une appréciation positive des citoyens face à ces mesures pourrait entrainer davantage d’initiatives en mobilité lente à Montréal <a class="reference-link" href="https://www.ledevoir.com/societe/576952/coronavirus-la-vie-a-deux-metres-de-distance">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="http://plus.lapresse.ca/screens/515d6d89-7cf2-44fb-aec9-93fbf0a63d73__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. D&rsquo;autant plus que les citoyens go&ucirc;tent maintenant &agrave; un nouveau mode de vie avec les mesures visant &agrave; encourager la marche et le v&eacute;lo <a class="reference-link" href="https://journalmetro.com/actualites/montreal/2446277/plusieurs-axes-reamenages-pour-les-pietons-et-les-cyclistes-a-montreal/">Réf{{'\xa0'}}&#x1f855;</a>. Patrick Bonin de <i>Greenpeace </i>esp&egrave;re que celles-ci perdureront consid&eacute;rant qu&rsquo;elles am&eacute;liorent la qualit&eacute; de vie, la sant&eacute; et l&rsquo;environnement <a class="reference-link" href="https://journalmetro.com/actualites/montreal/2446277/plusieurs-axes-reamenages-pour-les-pietons-et-les-cyclistes-a-montreal/">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			
			<h3>Quelles sont les initiatives municipales qui génèrent des changements sociaux dans l’espace public montréalais{{'\xa0'}}?</h3>
			<p>Durant la crise de la COVID-19, la Ville de Montr&eacute;al a mis en place un <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100">plan estival</a> de d&eacute;confinement mettant de l&rsquo;avant une ville plus lente, en favorisant la marche et le v&eacute;lo au d&eacute;triment de l&rsquo;automobile <a class="reference-link" href="https://montreal.ca/articles/les-voies-actives-securitaires-un-plan-de-deplacements-estival">Réf{{'\xa0'}}&#x1f855;</a>. Ceci soul&egrave;ve que les rapports sociaux en fonction de l&rsquo;espace occup&eacute; dans Montr&eacute;al par les automobilistes, cyclistes et pi&eacute;tons est en changement.</p>


			<h2>&Eacute;conomie / <br/><em>confinement</em></h2>
			
			<h3>Quelles sont les aspirations des Montr&eacute;alais concernant l&rsquo;importance de consommer &laquo;{{'\xa0'}}local{{'\xa0'}}&raquo;{{'\xa0'}}?</h3>
			<p>Durant la crise de la COVID-19, l&rsquo;importance de consommer &laquo;{{'\xa0'}}local{{'\xa0'}}&raquo; a &eacute;t&eacute; soulev&eacute;e &agrave; de nombreuses reprises par le gouvernement pour encourager l&rsquo;&eacute;conomie qu&eacute;b&eacute;coise en crise &agrave; cause du confinement <a class="reference-link" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?idArticle=2804054300">Réf{{'\xa0'}}&#x1f855;</a>. Dans les m&eacute;dias, les opinions sur l&rsquo;engouement pour les achats locaux sont partag&eacute;es. Certains &eacute;voquent que les Qu&eacute;b&eacute;cois poursuivront leurs achats locaux <a class="reference-link" href="https://plus.lapresse.ca/screens/be5c8139-7a94-4c7c-be35-9ce53c29e1bb__7C___0.html">Réf{{'\xa0'}}&#x1f855;</a>, alors que d&rsquo;autres ont soulevé que l'int&eacute;r&ecirc;t pour le «{{'\xa0'}}local{{'\xa0'}}» ne restera pas n&eacute;cessairement consid&eacute;rant qu'apr&egrave;s une p&eacute;riode de restriction dans l'histoire, une p&eacute;riode de rel&acirc;chement s'en suit <a class="reference-link" href="https://plus.lapresse.ca/screens/7a745908-a14e-44a6-8aa8-2d4b8c7c4a89__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Paradoxalement, Sylvain Pelletier, commer&ccedil;ant du March&eacute; Jean-Talon, a soulevé que le gouvernement a &eacute;mis des mesures contradictoires concernant le commerce «{{'\xa0'}}local{{'\xa0'}}» en permettant aux magasins de grandes surfaces de poursuivre leurs ventes le dimanche, alors que les petits commer&ccedil;ants se voyaient forcer de fermer cette m&ecirc;me journ&eacute;e <a class="reference-link" href="https://www.ledevoir.com/societe/consommation/577981/l-ete-prend-ses-quartiers-au-marche-jean-talon">Réf{{'\xa0'}}&#x1f855;</a>. Tout de m&ecirc;me, une campagne de financement dans l'arrondissement de Mercier&ndash;Hochelaga-Maisonneuve nomm&eacute; <i>J'ach&egrave;te local dans MHM</i> a d&eacute;passé son objectif de 230 % en 48 heures soulignant le soutien des Montr&eacute;alais envers les commer&ccedil;ants locaux <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32650">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>&Agrave; propos de l&rsquo;alimentation, les journalistes indiquent que les Montr&eacute;alais se sont int&eacute;ressés davantage aux &eacute;piceries de quartier et aux bi&egrave;res et vins qu&eacute;b&eacute;cois <a class="reference-link" href="https://www.ledevoir.com/vivre/alimentation/578537/coronavirus-l-epicerie-de-quartier-a-la-rescousse">Réf{{'\xa0'}}&#x1f855;</a>. Tandis qu'&agrave; l&rsquo;&eacute;chelle du territoire, d&egrave;s le 15{{'\xa0'}}avril, le gouvernement a proposé un plan de relance &eacute;conomique consistant &agrave; augmenter de 50% la part de l'assiette des Qu&eacute;b&eacute;cois qui provient des fermes locales <a class="reference-link" href="https://www.ledevoir.com/economie/577007/relance-economique-quebec-invite-a-accelerer-des-projets-en-vue-de-l-apres-crise">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Somme toute, les opinions des journalistes et les mesures prises pour encourager la consommation de produits locaux sont divis&eacute;es. Ceci indique qu&rsquo;il est encore trop t&ocirc;t pour d&eacute;terminer si les aspirations face &agrave; la consommation de produits locaux resteront une pr&eacute;occupation aupr&egrave;s des citoyens qu&eacute;b&eacute;cois.</p>
			
			<h3>Quels sont les défis et les enjeux associés envers les artères commerciales et les mesures sanitaires{{'\xa0'}}?</h3>
			<p>Durant le confinement, les grandes art&egrave;res commerciales des quartiers montr&eacute;alais ont subi des changements pour répondre au défi de la distanciation physique, dont l&rsquo;accueil de corridors sanitaires <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>. Un corridor sanitaire r&eacute;pond au besoin de distanciation en cette p&eacute;riode de pand&eacute;mie en offrant plus d&rsquo;espace pour les pi&eacute;tons pour circuler et faire la file d&rsquo;attente au d&eacute;triment des espaces de stationnement dans la rue <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>. Cette mesure d&eacute;courage d&rsquo;autant plus les acheteurs &agrave; se d&eacute;placer en auto pour venir aux magasins. La premi&egrave;re rue commer&ccedil;ante &agrave; mettre en place un corridor sanitaire &eacute;tait l&rsquo;avenue Mont-Royal en date du 14{{'\xa0'}}avril 2020 <a class="reference-link" href="https://montrealgazette.com/business/local-business/montreal-to-decide-on-new-health-corridors-by-weeks-end-plateau-mayor/">Réf{{'\xa0'}}&#x1f855;</a>. L&rsquo;initiative s&rsquo;est par la suite multipli&eacute;e sur plusieurs rues{{'\xa0'}}dans Ville-Marie, Verdun, le Sud-Ouest, Mercier&ndash;Hochelaga-Maisonneuve, Rosemont-La-Petite-Patrie, Outremont, C&ocirc;te-Des-Neiges-Notre-Dame-De-Gr&acirc;ce, Le Plateau-Mont-Royal, Ahuntsic-Cartierville <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32575">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Le 4{{'\xa0'}}mai 2020 les commerces sur rue étaient ouverts dans l&rsquo;ensemble du Qu&eacute;bec <a class="reference-link" href="https://www.ledevoir.com/politique/quebec/577857/coronavirus-point-de-presse-legault-28-avril">Réf{{'\xa0'}}&#x1f855;</a>. Cependant, &agrave; Montr&eacute;al les commerces sur rue ont ouvert seulement 25{{'\xa0'}}mai 2020 <a class="reference-link" href="https://journalmetro.com/actualites/montreal/2446834/les-commerces-pourront-rouvrir-le-25-mai-a-montreal/">Réf{{'\xa0'}}&#x1f855;</a>. En amont, les centres commerciaux n&rsquo;ont toujours pas pr&eacute;senté pas de dates de r&eacute;ouverture. De plus, en date du 6{{'\xa0'}}mai 2020, la pi&eacute;tonnisation de l&rsquo;avenue Wellington, une art&egrave;re commerciale &agrave; Verdun <a class="reference-link" href="https://montreal.ca/actualites/declaration-sur-la-pietonnisation-de-la-rue-wellington">Réf{{'\xa0'}}&#x1f855;</a> a encourag&eacute; d&rsquo;autres arrondissements montr&eacute;alais &agrave; faire de m&ecirc;me &agrave; partir du 15{{'\xa0'}}mai lors du d&eacute;voilement du <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100">Plan estival de la ville de Montr&eacute;al</a> <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Un enjeu principal subsiste concernant les terrasses de restaurants. En effet, en date du 24{{'\xa0'}}mars 2020, Montr&eacute;al craignait ne pas avoir de terrasses sur ses rues pour la p&eacute;riode estivale <a class="reference-link" href="https://plus.lapresse.ca/screens/29aa14be-d20a-4ee3-8c90-f08545f6f572__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a>. D&rsquo;autres journalistes ont propos&eacute; de fermer les rues aux automobiles pour avoir acc&egrave;s &agrave; davantage d&rsquo;espace pour que les restaurants aient des terrasses distanci&eacute;es <a class="reference-link" href="https://www.ledevoir.com/societe/577987/un-ete-sans-fraicheur-ni-trempette">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En définitive, le défi de la distanciation physique a forcé la mise en oeuvre des corridors sanitaires <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32575">Réf{{'\xa0'}}&#x1f855;</a>, de la pi&eacute;tonnisation des artères commerciales <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a> et a semé le doute concernant l'ouverture des terrasses de restaurants <a class="reference-link" href="https://www.ledevoir.com/societe/577987/un-ete-sans-fraicheur-ni-trempette">Réf{{'\xa0'}}&#x1f855;</a></p>
			
			<h3>La mobilité des travailleurs dans le territoire urbain a-t-elle été l’objet de préoccupations lors du confinement montréalais{{'\xa0'}}?</h3>
			<p>Durant le confinement, la Soci&eacute;t&eacute; des Transports de Montr&eacute;al (STM) a soulev&eacute; l&rsquo;impossibilit&eacute; de transporter les usagers vers leur lieu de travail tout en respectant les mesures de distanciation <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1701725/ctt-stm-transports-covid19-distanciation-impossible-deconfinement">Réf{{'\xa0'}}&#x1f855;</a>. Pour tenter de trouver une solution, la STM a entam&eacute; des discussions avec la Chambre de commerce du Montr&eacute;al m&eacute;tropolitain (CCMM) pour encourager les employeurs &agrave; &eacute;taler les horaires des travailleurs sur diff&eacute;rentes plages horaires et par le fait m&ecirc;me r&eacute;duire l&rsquo;achalandage de passagers aux heures de pointe <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/578594/la-stm-distribuera-des-masques-a-ses-usagers">Réf{{'\xa0'}}&#x1f855;</a>. De plus, cette redistribution des horaires des travailleurs permettrait de r&eacute;duire la congestion sur les routes <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-04-29/mobilite-montreal-prepare-l-apres-confinement">Réf{{'\xa0'}}&#x1f855;</a>. Une &eacute;tude de la {{'\xa0'}}Chaire de mobilit&eacute; de l&rsquo;&eacute;cole Polytechnique évoque aussi que si le t&eacute;l&eacute;travail restait en place pour le cinqui&egrave;me des travailleurs ceci permettrait une baisse de 10% des &eacute;missions gaz &agrave; effet au Qu&eacute;bec <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-04-29/mobilite-montreal-prepare-l-apres-confinement">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Nombreux sont les travailleurs essentiels dans les centres d&rsquo;h&eacute;bergement et de soins de longue dur&eacute;e (CHSLD) de Montr&eacute;al qui r&eacute;sident &agrave; Montr&eacute;al-Nord, ceux-ci pour se rendre sur leur lieu de travail utilisent pour la plupart les transports en commun. Consid&eacute;rant que ces travailleurs ont été directement en contact avec des personnes infect&eacute;es par la COVID-19, leurs d&eacute;placements dans les transports en commun ont repr&eacute;senté un vecteur de contagion qui a été un facteur de la hausse des cas de COVID-19 &agrave; Montr&eacute;al-Nord <a class="reference-link" href="https://journalmetro.com/local/montreal-nord/2443637/travailler-a-se-rendre-malade-a-montreal-nord/">Réf{{'\xa0'}}&#x1f855;</a>.</p>


			<h2>Mode de vie / <br/><em>confinement</em></h2>
			
			<h3>Quels sont les impacts de la COVID-19 sur les modes de vie, la qualité du cadre de vie et le bien-être des Montréalais{{'\xa0'}}?</h3>
			<p>Concernant les modes de vie urbains, les m&eacute;dias ont rapporté depuis le d&eacute;but du confinement une peur chez les citoyens de la grande densit&eacute; de la ville. Ils ont soulevé qu&rsquo;un confinement dans une maison de banlieue et une cour arri&egrave;re est davantage valoris&eacute;, tout comme de se d&eacute;placer en automobile et de faire des achats uniquement dans des commerces de grandes surfaces <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/576932/faire-de-la-ville-un-havre-du-vivre-ensemble">Réf{{'\xa0'}}&#x1f855;</a>. De plus, les citoyens vivant dans des tours d&rsquo;habitation mentionnent que la vie de copropri&eacute;t&eacute; est bien moins agr&eacute;able depuis qu&rsquo;il n&rsquo;est plus possible de profiter des espaces communs et de tenir les assembl&eacute;es g&eacute;n&eacute;rales <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694864/condos-coproprietes-syndicats-questions-coronavirus-covid-19?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Au niveau des sorties, les Montr&eacute;alais, ne poss&eacute;dant pas de cour arri&egrave;re pour la plupart, ont profité des parcs urbains lorsque la temp&eacute;rature était cl&eacute;mente, ce qui mené &agrave; un plus grand achalandage qu&rsquo;en situation normale selon les m&eacute;dias <a class="reference-link" href="https://www.lapresse.ca/covid-19/202005/04/01-5272009-forte-affluence-dans-les-parcs-la-situation-est-elle-maitrisee.php">Réf{{'\xa0'}}&#x1f855;</a>. Alors que les sorties dans les restaurants, les bars, les caf&eacute;s, les th&eacute;&acirc;tres ne faisaient plus partie du quotidien des citadins <a class="reference-link" href="https://www.ledevoir.com/societe/578233/montreal-la-nuit">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}}</p>
			<p>Au cours du confinement, le jardinage a suscité un intérêt chez les Montr&eacute;alais. En effet, les m&eacute;dias rapportent que les Montr&eacute;alais s&rsquo;int&eacute;ressent davantage au jardinage et &agrave; l&rsquo;agriculture urbaine, car ce loisir permet de connecter avec la nature, d&rsquo;&eacute;vacuer le stress et de d&eacute;velopper une autonomie alimentaire en temps de crise <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/577752/la-pandemie-terreau-fertile-pour-les-apprentis-jardiniers">Réf{{'\xa0'}}&#x1f855;</a>. De plus, les jardins communautaires ont ouvert le 15{{'\xa0'}}avril 2020 malgr&eacute; les mesures de distanciation en raison de la forte demande de la population aux institutions gouvernementales <a class="reference-link" href="https://www.ledevoir.com/societe/576952/coronavirus-la-vie-a-deux-metres-de-distance">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}}</p>
			<p>Durant le confinement, la pratique de nombreux sports en centre est devenue impossible, cependant les citoyens ont soulevé que certains sports peuvent &ecirc;tre pratiqu&eacute;s en respectant les mesures de distanciation. En r&eacute;ponse, le gouvernement a permis &agrave; partir du 20{{'\xa0'}}mai l&rsquo;ouverture des terrains de golf, v&eacute;lo, tennis, randonn&eacute;e, escalade et la pratique des sports aquatiques sur des bateaux simples <a class="reference-link" href="https://montrealgazette.com/sports/quebec-announces-a-gradual-reopening-of-outdoor-sports-on-may-20/">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Du c&ocirc;t&eacute; du bien-&ecirc;tre, les avions &eacute;tant clou&eacute;s au sol par la pand&eacute;mie, les quartiers qui étaient g&eacute;n&eacute;ralement affect&eacute;s par la nuisance sonore de ceux-ci, soient Villeray, Dorval, Pointe-Claire et Saint-Laurent, ont été reconnaissants du paysage sonore plus serein depuis ce changement drastique <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/578203/l-inhabituel-silence-des-avions">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Dans le m&ecirc;me ordre d&rsquo;id&eacute;es, les d&eacute;placements en automobile étaient beaucoup moins nombreux en raison du confinement, ainsi les rues n'étaient presque plus utilis&eacute;es par les voitures <a class="reference-link" href="https://plus.lapresse.ca/screens/af46b3e2-8ff4-4c87-a743-6bcd9e8773d3__7C___0.html?utm_medium=Email&amp;utm_campaign=Internal+Share&amp;utm_content=Screen">Réf{{'\xa0'}}&#x1f855;</a>. Les adolescents et les enfants ont commenc&eacute; &agrave; s&rsquo;approprier la rue pour y jouer. Pour assurer la s&eacute;curit&eacute; et la distanciation d&eacute;j&agrave; trois rues en date du 2{{'\xa0'}}mai 2020 étaient pi&eacute;tonnis&eacute;es au Plateau-Mont-Royal <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1699520/coronavirus-covid-rues-pietonnes-transport-actif?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>. Les pi&eacute;tons continuant d&rsquo;affluer dans les rues de Montr&eacute;al, la Ville de Montr&eacute;al a proposé en date du 15{{'\xa0'}}mai 2020 un plan estival qui comporte la pi&eacute;tonnisation de plusieurs rues <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32651&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Concernant le mode de vie, les d&eacute;placements &agrave; v&eacute;lo ont été davantage valoris&eacute;s, d&rsquo;autant plus que les v&eacute;los BIXI sont maintenant consid&eacute;r&eacute;s comme un moyen de transport collectif au m&ecirc;me titre que les autobus et le m&eacute;tro <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694064/bixi-debute-saison-abonnements-gratuit-employes-sante">Réf{{'\xa0'}}&#x1f855;</a>. Cependant, la grande affluence sur les pistes cyclables a emp&ecirc;ché de respecter une distanciation sociale respectable. Le <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100">Plan estival de la ville de Montr&eacute;al</a> propose l&rsquo;implantation de 327 km de nouvelles pistes cyclables <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1703312/plan-deplacement-montreal-pandemie-voies-securitaires">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}}</p>
			<p>En d&eacute;finitive, un regain d&rsquo;int&eacute;r&ecirc;t dans la population pour le v&eacute;lo, le jardinage, le sport et les sorties au parc a été rapport&eacute; par les m&eacute;dias.</p>

			<h3>Quelles sont les actions citoyennes qui prennent corps dans l&rsquo;espace public{{'\xa0'}}?</h3>
			<p>Dans l&rsquo;arrondissement Villeray-Saint-Michel-Parc-Extension, les citoyens ont encouragé les commer&ccedil;ants de leur quartier en &eacute;laborant un syst&egrave;me de livraison &agrave; v&eacute;lo. Cette action citoyenne prenant de l&rsquo;ampleur, la Ville de Montr&eacute;al a offert de l&rsquo;aide <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32618&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>. &Eacute;galement dans Montr&eacute;al-Nord, un des quartiers les plus d&eacute;munis de Montr&eacute;al et fortement touch&eacute;s par la COVID-19, un syst&egrave;me de distribution de masques a &eacute;t&eacute; mis en place par les citoyens <a class="reference-link" href="https://journalmetro.com/local/montreal-nord/2442201/masques-gratuits-et-corridors-sanitaires-a-montreal-nord/?fbclid=IwAR0MWd8tPgINnPck2iZOnoB9vuVM1gf1mGpWXv-mdPPLfjhDmPblBsa9fhU">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Sur une note plus positive, pour &eacute;gayer les ruelles de Mercier&ndash;Hochelaga-Maisonneuve, le collectif <i>Bonheur Mobile</i> regroupant des artistes du cirque se retrouvant sans contrats en raison du confinement organisait des d&eacute;fil&eacute;s dans les ruelles <a class="reference-link" href="https://www.journaldemontreal.com/2020/05/07/hochelaga-maisonneuve--bonheur-mobile-pour-egayer-les-ruelles">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Concernant les espaces de vie privée ou publique, quelles sont les mesures engagées pour satisfaire les besoins de la population{{'\xa0'}}?</h3>
			<p>Dans les m&eacute;dias, il est soulev&eacute; que le confinement est vécu de mani&egrave;re in&eacute;gale consid&eacute;rant que la population r&eacute;side dans des logements de taille et qualit&eacute; diff&eacute;rentes selon les arrondissements. Il ne peut &ecirc;tre pratiqu&eacute; dans le confort par tous <a class="reference-link" href="https://plus.lapresse.ca/screens/ff83c3e0-b983-42ae-9d85-f2de0fbcd024__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. De plus, Montr&eacute;al traversait simultan&eacute;ment une p&eacute;nurie de logements <a class="reference-link" href="https://www.lapresse.ca/debats/editoriaux/2020-01-22/logement-pas-encore-la-crise-mais">Réf{{'\xa0'}}&#x1f855;</a>. Pour que celle-ci ne s'empire pas, le gouvernement qu&eacute;b&eacute;cois a ouvert les chantiers de construction en date 20{{'\xa0'}}avril 2020 pour &eacute;viter que des locataires ne puissent pas acc&eacute;der &agrave; leur logement lors des d&eacute;m&eacute;nagements habituellement le 1<sup>er</sup>{{'\xa0'}}juillet <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1693975/coronavirus-construction-chantiers-apchq-entrevue">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>La crise sanitaire et les mesures de confinement ont été difficilement applicables pour les itin&eacute;rants, la Ville de Montr&eacute;al a r&eacute;quisitionn&eacute; quatre h&ocirc;tels vides pour h&eacute;berger ces personnes et leur offrir un milieu de vie r&eacute;pondant &agrave; leurs besoins <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1691992/hotels-sans-abris-itinerants-covid-toronto-montreal">Réf{{'\xa0'}}&#x1f855;</a>. Cette mesure solidaire aspire &agrave; mettre fin &agrave; l&rsquo;itin&eacute;rance &agrave; Montr&eacute;al. La Ville de Montr&eacute;al souligne aussi que la Biblioth&egrave;que des Archives nationales du Qu&eacute;bec est un rep&egrave;re r&eacute;confortant pour plus de 200 itin&eacute;rants, bien que celle-ci soit ferm&eacute;e au grand public, elle s&rsquo;est transform&eacute;e en halte-r&eacute;pit <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694077/montreal-haltes-ouverture-personnes-sans-abri-itinerant-coronavirus">Réf{{'\xa0'}}&#x1f855;</a>. Cette initiative souligne que l&rsquo;espace de vie de ces derniers reste valoris&eacute;.</p>
			<p>Espaces de vie publique, les jardins communautaires ont des impacts positifs (aide alimentaire, augmentation de la consommation de fruits et l&eacute;gumes, augmentation de l&rsquo;activit&eacute; physique, r&eacute;duction du stress) sur la sant&eacute; des adeptes &laquo;{{'\xa0'}}jardiniers{{'\xa0'}}&raquo;. De ce fait, l&rsquo;Institut national de sant&eacute; publique du Qu&eacute;bec (INSPQ) a accepté leur ouverture <a class="reference-link" href="https://plus.lapresse.ca/screens/26a0afa8-70f5-46e4-ad3a-ca15bf861390__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. De plus, dans les m&eacute;dias, il est &eacute;voqu&eacute; que le confinement permettrait de retrouver une certaine &eacute;chelle humaine dans nos activit&eacute;s &agrave; la maison <a class="reference-link" href="https://lactualite.com/societe/aimerons-nous-encore-la-ville/">Réf{{'\xa0'}}&#x1f855;</a>. Ainsi, cette p&eacute;riode de confinement peut mener &agrave; une revalorisation des espaces de vie priv&eacute;e et publique.</p>

			<h3>&Agrave; la suite du confinement montréalais, quels changements peut-on attendre de la part des individus, d’actions collectives, municipales et gouvernementales{{'\xa0'}}?</h3>
			<p>Selon les m&eacute;dias, les Montr&eacute;alais patientaient depuis longtemps pour que le gouvernement municipal offre plus d&rsquo;espace pour la circulation pi&eacute;tonne et cycliste &agrave; Montr&eacute;al <a class="reference-link" href="https://plus.lapresse.ca/screens/bcc22c32-aedc-4fb5-972f-1f67e018adf5__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. De plus, si ces initiatives sont appr&eacute;ci&eacute;es par les citoyens ceci pourrait avoir un impact direct sur l&rsquo;appropriation de la ville, entre autres, en am&eacute;nageant Montréal davantage &agrave; une &eacute;chelle de proximité <a class="reference-link" href="https://journalmetro.com/actualites/montreal/2446277/plusieurs-axes-reamenages-pour-les-pietons-et-les-cyclistes-a-montreal/">Réf{{'\xa0'}}&#x1f855;</a>. D&rsquo;autant plus que les voies actives s&eacute;curitaires ont offert un espace sans le danger des automobilistes pour circuler &agrave; pied ou &agrave; v&eacute;lo <a class="reference-link" href="https://montreal.ca/articles/les-voies-actives-securitaires-un-plan-de-deplacements-estival">Réf{{'\xa0'}}&#x1f855;</a>. Notamment, il est soulev&eacute; que les mesures que la Ville de Montr&eacute;al a mises en place depuis le 15{{'\xa0'}}mai 2020 pourraient &ecirc;tre conserv&eacute;es en &eacute;t&eacute; au-del&agrave; de la crise sanitaire <a class="reference-link" href="https://plus.lapresse.ca/screens/ed0eaeba-c84a-4ecc-a875-7caf8ebbf2e3__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Chez les diff&eacute;rents groupes sociaux, il est rapport&eacute; que les a&icirc;n&eacute;s vont s&ucirc;rement rester marqu&eacute;s par la crise et avoir moins d&rsquo;int&eacute;r&ecirc;t &agrave; retourner dans l&rsquo;espace public, cependant les autres groupes de la soci&eacute;t&eacute; attendaient particuli&egrave;rement l&rsquo;annonce du  <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&amp;extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100"><i>Plan estival de la Ville de Montr&eacute;al</i></a> <a class="reference-link" href="https://www.ledevoir.com/societe/577987/un-ete-sans-fraicheur-ni-trempette">Réf{{'\xa0'}}&#x1f855;</a> ce qui soul&egrave;ve une envie de se r&eacute;approprier la ville apr&egrave;s une p&eacute;riode de confinement. De plus, au cours de la crise, l&rsquo;importance des parcs pour le bien-&ecirc;tre psychologique des citadins a &eacute;t&eacute; valoris&eacute;e par les citadins et les autorit&eacute;s municipales <a class="reference-link" href="https://plus.lapresse.ca/screens/ff83c3e0-b983-42ae-9d85-f2de0fbcd024__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Alors que le v&eacute;lo et la marche ont gagné en popularit&eacute;, les Montr&eacute;alais ont vécu suite au confinement un traumatisme face aux transports en commun. Ceci pourrait encourager l&rsquo;utilisation de l&rsquo;automobile et par le fait m&ecirc;me augmenter la congestion sur les routes <a class="reference-link" href="https://www.ledevoir.com/societe/576952/coronavirus-la-vie-a-deux-metres-de-distance">Réf{{'\xa0'}}&#x1f855;</a>. Tout de m&ecirc;me, le plan de relance &eacute;conomique orchestr&eacute; par la Ville de Montr&eacute;al a proposé un d&eacute;veloppement des services de transport en commun <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1693999/causerie-ccmm-leblanc-coronavirus-covid-19-etat-urgence-bixi?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Concernant les actions collectives, l&rsquo;OBNL  <a class="reference-link" href="https://www.pepiniere.co/mission-et-vision"><i>la P&eacute;pini&egrave;re</i></a> a proposé d'aménager de grandes terrasses dans les parcs permettant aux restaurants de reprendre certaines activit&eacute;s, tout en conservant les mesures de distanciation. L&rsquo;organisme a suggéré aussi aux commer&ccedil;ants qui ont pignon de rue d&rsquo;utiliser &agrave; leur avantage leur vitrine pour encourager l&rsquo;achat local <a class="reference-link" href="https://plus.lapresse.ca/screens/e272d5e3-26e0-459e-b7a2-4a03fd8b6b5d__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En ce qui a trait aux actions collectives des entreprises, la crise sanitaire semble prouver &agrave; court terme l&rsquo;efficacit&eacute; du t&eacute;l&eacute;travail. Face &agrave; la crise &eacute;conomique, les entreprises devront r&eacute;viser leurs d&eacute;penses et ceci pourrait engendrer un d&eacute;clin du centre-ville par manque de financement pour la location d&rsquo;un espace de travail dans ce secteur <a class="reference-link" href="https://plus.lapresse.ca/screens/7a745908-a14e-44a6-8aa8-2d4b8c7c4a89__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Au niveau du gouvernement, la crise COVID-19 a mis &agrave; d&eacute;couvert la fragilit&eacute; du syst&egrave;me de sant&eacute; &agrave; Montr&eacute;al et la difficult&eacute; &agrave; respecter les mesures de distanciation dans les quartiers d&eacute;munis et denses (Montr&eacute;al-Nord <a class="reference-link" href="https://plus.lapresse.ca/screens/bcfef450-1b54-452e-bd28-c12653ae7070__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>, Mercier-Hochelaga-Maisonneuve <a class="reference-link" href="https://montrealgazette.com/news/local-news/analysis-why-is-the-covid-19-death-rate-soaring-in-hochelaga-maisonneuve">Réf{{'\xa0'}}&#x1f855;</a>). D&rsquo;autant plus que dans ces m&ecirc;mes quartiers, il y a un manque de vastes espaces verts publics. L&rsquo;exposition de ces probl&egrave;mes risque de forcer le gouvernement &agrave; investir davantage en sant&eacute; publique, et ce dans les arrondissements les plus d&eacute;munis <a class="reference-link" href="https://plus.lapresse.ca/screens/bcfef450-1b54-452e-bd28-c12653ae7070__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a> .</p>


			<h2>Inclusion / <br/><em>confinement</em></h2>
			
			<h3>L’espace public montréalais est-il inclusif ou exclusif{{'\xa0'}}?</h3>
			<p>Les diff&eacute;rentes mesures organis&eacute;es par la Ville de Montr&eacute;al dans l&rsquo;espace public, soit la mise en place de cinq centres de jours ext&eacute;rieurs pour itin&eacute;rants <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32517">Réf{{'\xa0'}}&#x1f855;</a>, d&rsquo;une clinique de d&eacute;pistage sur la place des Festivals <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-04-20/la-clinique-covid-demantelee-au-centre-ville-de-montreal">Réf{{'\xa0'}}&#x1f855;</a> et d&rsquo;annexes d&rsquo;h&ocirc;pital &agrave; Verdun <a class="reference-link" href="https://ciusss-centresudmtl.gouv.qc.ca/actualite/covid-19-ouverture-prochaine-dune-annexe-lhopital-de-verdun">Réf{{'\xa0'}}&#x1f855;</a> et &agrave; LaSalle <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32590">Réf{{'\xa0'}}&#x1f855;</a> soulignent que l&rsquo;espace public montr&eacute;alais s&rsquo;est adapté aux besoins de la population et est par le fait m&ecirc;me inclusif.</p>
			<p>En proposant davantage de voies pour les pi&eacute;tons et les v&eacute;los au lieu d'encourager l'utilisation de l'automobile, la Ville de Montr&eacute;al a semblé favoriser les transports actifs qui sont par le fait m&ecirc;me plus abordables et &eacute;cologiques <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-04-29/mobilite-montreal-prepare-l-apres-confinement">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>&Agrave; propos des <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694988/trottoir-elargi-corridors-sanitaires-commerces-services?fromApp=appInfoIos&amp;partageApp=appInfoiOS&amp;accesVia=partage">corridors sanitaires</a>, Le Plateau-Mont-Royal, un quartier bien nanti, a &eacute;t&eacute; le premier &agrave; accueillir cette nouvelle mesure <a class="reference-link" href="https://montrealgazette.com/business/local-business/montreal-to-decide-on-new-health-corridors-by-weeks-end-plateau-mayor/">Réf{{'\xa0'}}&#x1f855;</a>. {{'\xa0'}}Cependant, la rue commer&ccedil;ante Ontario dans l&rsquo;arrondissement Mercier&ndash;Hochelaga-Maisonneuve, un quartier plus d&eacute;muni, a d&eacute;ploré l&rsquo;absence de corridors sanitaires <a class="reference-link" href="https://plus.lapresse.ca/screens/f510fc25-89f7-44f3-8e93-a498f2b6f6c4__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>. Ceci souligne que les espaces publics inclusifs sont plus fr&eacute;quents dans les quartiers les mieux nantis.</p>

			<h3>Y -a-t-il des actions engagées à Montréal concernant la solidarité et la dignité humaine{{'\xa0'}}?</h3>
			<p>Concernant les itinérants, au d&eacute;but de la crise, les dortoirs des organismes à but non lucratif (OBNL) pour sans-abris ont hésité à fermer de peur que la situation s'empire. Tout de m&ecirc;me, les OBNL ont d&eacute;ploy&eacute; des mesures d'hygi&egrave;ne en offrant des masques pour permettre &agrave; la client&egrave;le et aux b&eacute;n&eacute;voles de se prot&eacute;ger <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1671967/montreal-covid-19-sans-abri-vulnerable-salubrite-desinfection-prevention">Réf{{'\xa0'}}&#x1f855;</a>. Aussi, du mat&eacute;riel sanitaire, tel des produits nettoyants, d&eacute;sinfectants et des lingettes sont mis &agrave; disposition pour les organismes qui viennent en aide aux itin&eacute;rants <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1678832/coronavirus-itinerants-montreal-aide-sans-abri-isolement-covid-19">Réf{{'\xa0'}}&#x1f855;</a>. &Agrave; la suite de la fermeture des dortoirs, pour promouvoir la dignit&eacute; urbaine, Montr&eacute;al a r&eacute;quisitionn&eacute; quatre h&ocirc;tels pour permettre aux itin&eacute;rants d'&ecirc;tre h&eacute;berg&eacute;s et de se faire tester pour la COVID-19 <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1693445/coronavirus-itinerants-sans-abri-montreal-covid-injections-supervisees">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}} De plus, l'ouverture de centre de jours, d'h&eacute;bergements d'urgence et de halte-r&eacute;pits pour les itin&eacute;rants est une action solidaire de la Ville de Montr&eacute;al <a class="reference-link" href="https://www.newswire.ca/fr/news-releases/covid-19-la-ville-de-montreal-deploie-une-nouvelle-serie-de-mesures-pour-soutenir-les-personnes-en-situation-d-itinerance-876843727.html?fbclid=IwAR3XsK5DW-bgKSAhRiO82OS4V9gmAdgvEHIEo1afqNvtE-GrLEbyadj6wew">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Pour les personnes en situation alimentaire pr&eacute;caire, la caf&eacute;t&eacute;ria de l&rsquo;organisation des jeunes de Parc-Extension (PEYO) a &eacute;t&eacute; convertie en entrep&ocirc;t o&ugrave; sont rang&eacute;es les denr&eacute;es alimentaires. Avec la collaboration de l&rsquo;organisme Ressources action-alimentation de Parc-Extension, des paniers ont &eacute;t&eacute; livr&eacute;s &agrave; quelque 600 m&eacute;nages depuis le 13{{'\xa0'}}mars <a class="reference-link" href="https://www.ledevoir.com/politique/montreal/578424/inquietude-dans-parc-extension">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En ce qui a trait au syst&egrave;me de sant&eacute;, pour respecter la dignit&eacute; d&rsquo;un maximum de personnes, le CIUSS de l&rsquo;Ouest-de-l&rsquo;&Icirc;le-de-Montr&eacute;al <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32590">Réf{{'\xa0'}}&#x1f855;</a> et l&rsquo;h&ocirc;pital de Verdun <a class="reference-link" href="https://ciusss-centresudmtl.gouv.qc.ca/actualite/covid-19-ouverture-prochaine-dune-annexe-lhopital-de-verdun">Réf{{'\xa0'}}&#x1f855;</a> ont am&eacute;nag&eacute; des annexes dans des lieux publics, des patients ont aussi &eacute;t&eacute; trait&eacute;s au sein de l&rsquo;h&ocirc;tel Place Dupuis, en raison de la solidarit&eacute; du propri&eacute;taire <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1696033/coronavirus-place-dupuis-patients-chambres-hotel">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Montr&eacute;al a agi face &agrave; ces enjeux, soient la solidarit&eacute; et la dignit&eacute; humaine, en &eacute;laborant des solutions face au probl&egrave;me d&rsquo;itin&eacute;rance pr&eacute;sent avant la crise, d&rsquo;autant plus que de nouvelles personnes se sont retrouv&eacute;es sans logement &agrave; cause de la crise <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1691992/hotels-sans-abris-itinerants-covid-toronto-montreal">Réf{{'\xa0'}}&#x1f855;</a>. De plus, le d&eacute;bordement des h&ocirc;pitaux n&eacute;cessitant ainsi de l'espace suppl&eacute;mentaire &nbsp;met en lumi&egrave;re les failles du syst&egrave;me de sant&eacute; <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32590">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Durant le confinement montréalais, quelle est l’importance accordée à la solidarité et la dignité humaine par les autorités locales{{'\xa0'}}?</h3>
			<p>Au d&eacute;but de la crise sanitaire, les centres d&rsquo;injection supervis&eacute;e ont &eacute;t&eacute; forc&eacute;s de fermer &agrave; l&rsquo;exception du Cactus. Pour les toxicomanes, il s'agit d'un service essentiel pour leur bien-&ecirc;tre et sant&eacute; <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1693445/coronavirus-itinerants-sans-abri-montreal-covid-injections-supervisees">Réf{{'\xa0'}}&#x1f855;</a>. Ceci met en lumi&egrave;re le manque de mat&eacute;riel pour le personnel, mais aussi l'in&eacute;galit&eacute; face &agrave; l'offre de soins chez les plus vuln&eacute;rables. De plus, les lourdes contraventions concernant la distanciation distribu&eacute;es par le Service de Police de la Ville de Montr&eacute;al (SPVM) touchent de mani&egrave;re disproportionn&eacute;e les plus d&eacute;munis, les personnes racis&eacute;es et les communaut&eacute;s marginalis&eacute;es qui sont le plus souvent victime de profilage <a class="reference-link" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?idArticle=2804150115">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1694424/pandemie-coronavirus-contravention-infraction-distanciation">Réf{{'\xa0'}}&#x1f855;</a>. <a class="reference-link" href="https://ccla.org/our_mission/?lang=fr">L'Association canadienne des libert&eacute;s civiles (ACLC)</a> a effectu&eacute; une demande d&rsquo;amnistie sur toutes les contraventions distribu&eacute;es pour raison de distanciation <a class="reference-link" href="https://www.lapresse.ca/covid-19/202004/19/01-5270027-covid-19-lamnistie-sera-reclamee-pour-les-contraventions.php">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Tout de m&ecirc;me, la Ville de Montr&eacute;al s&rsquo;est montr&eacute;e solidaire &agrave; d&rsquo;autres niveaux, entre autres elle continue d'appuyer financi&egrave;rement le projet de logements sociaux Vilavi-Lesp&eacute;rance <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32569">Réf{{'\xa0'}}&#x1f855;</a>. De plus, pour respecter la dignit&eacute; des itin&eacute;rants, la Ville de Montr&eacute;al avec l&rsquo;aide d&rsquo;Architecture sans fronti&egrave;res Qu&eacute;bec (ASFQ) <a class="reference-link" href="https://www.asf-quebec.org/appel-a-benevoles-corvee-communautaire-pour-les-sans-abri-le-mardi-24-mars/">Réf{{'\xa0'}}&#x1f855;</a> a ouvert de nombreux centres de jours, d&rsquo;h&eacute;bergements d&rsquo;urgence et de halte-r&eacute;pits <a class="reference-link" href="https://www.newswire.ca/fr/news-releases/covid-19-la-ville-de-montreal-deploie-une-nouvelle-serie-de-mesures-pour-soutenir-les-personnes-en-situation-d-itinerance-876843727.html?fbclid=IwAR3XsK5DW-bgKSAhRiO82OS4V9gmAdgvEHIEo1afqNvtE-GrLEbyadj6wew">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En mati&egrave;re de solidarit&eacute;, la Ville de Montr&eacute;al a mis sur place un programme de financement en ce temps de crise pour les petites entreprises montr&eacute;alaises et les organismes &agrave; but non lucratif (OBNL) <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32550&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>. De plus, la Ville de Montr&eacute;al est restée solidaire envers ses arrondissements en d&eacute;ployant de l&rsquo;aide particuli&egrave;rement dans Montr&eacute;al-Nord, un des quartiers les plus touch&eacute;s par la pand&eacute;mie <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32602">Réf{{'\xa0'}}&#x1f855;</a>. Elle a aussi encourag&eacute; la r&eacute;ouverture des jardins communautaires face &agrave; ses citoyens qui s&rsquo;assurent d&rsquo;une s&eacute;curit&eacute; et un soutien alimentaires <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32604">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			
			<h3>Durant le confinement, l’inclusion urbaine est-elle une préoccupation{{'\xa0'}}?</h3>
			<p>L'inclusion urbaine joue un r&ocirc;le important consid&eacute;rant que ce sont les m&eacute;nages &agrave; plus faible revenu qui sont les plus &agrave; risque de contracter la COVID-19, ainsi le gouvernement a inclu davantage d&rsquo;aides &agrave; ces communaut&eacute;s pour &eacute;viter que la crise s&eacute;visse dans l'enti&egrave;ret&eacute; de la soci&eacute;t&eacute;. <a class="reference-link" href="https://www.journaldemontreal.com/2020/05/05/la-covid-19-fait-plus-de-ravages-dans-les-quartiers-a-faible-revenu">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="https://www.journaldemontreal.com/2020/05/05/la-covid-19-fait-plus-de-ravages-dans-les-quartiers-a-faible-revenu">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32602">Réf{{'\xa0'}}&#x1f855;</a></p>
			<p>De plus, les personnes pr&eacute;caires, soient les femmes et les personnes racis&eacute;es sont surrepr&eacute;sent&eacute;es dans la crise <a class="reference-link" href="https://www.ledevoir.com/societe/577984/aux-confins-des-inegalites">Réf{{'\xa0'}}&#x1f855;</a>. Notamment, en ce temps de crise, Alain Croteau, pr&eacute;sident du Syndicat des travailleuses et des travailleurs du CIUSSS Centre-Sud-de-l'&Icirc;le-de-Montr&eacute;al soul&egrave;ve que la crise s'est produite principalement dans les centres d&rsquo;h&eacute;bergement et de soins de longue dur&eacute;e (CHSLD). De ce fait, les travailleurs sociaux et les pr&eacute;pos&eacute;s aux b&eacute;n&eacute;ficiaires étaient les premi&egrave;res personnes en contact avec les victimes de la COVID-19. Malheureusement, ces m&ecirc;mes personnes qui risquaient de contracter le virus sont aussi celles qui se font verser le salaire le plus bas dans le syst&egrave;me de sant&eacute; qu&eacute;b&eacute;cois. De plus, les pr&eacute;pos&eacute;es aux b&eacute;n&eacute;ficiaires sont principalement des femmes racis&eacute;es soulevant le manque d'inclusion et les diff&eacute;rences raciales pr&eacute;sentes dans les diff&eacute;rents r&ocirc;les de la soci&eacute;t&eacute;. Le peu d'aide financi&egrave;re et mat&eacute;rielle (les &eacute;quipements) a rappellé que les travailleurs dans les CHSLD manquent de soutien du gouvernement <a class="reference-link" href="https://ici.radio-canada.ca/premiere/emissions/tout-un-matin/segments/chronique/166242/femmes-racisees-exploitation-chsld-cisss-centre-sud?fbclid=IwAR2hDPTEiGt4Un7Y1lZKO8eohmLOg8WRKkZVRuEd-sPdRTH3dFjyMOiKZ5Q">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Quelles sont les mesures mises en œuvre pour venir en aide aux victimes de discrimination et d’exclusion{{'\xa0'}}?</h3>
			<p>Les a&icirc;n&eacute;s autonomes en centre de personnes &acirc;g&eacute;es ont été victimes de discrimination. En effet, ils s&rsquo;avéraient oblig&eacute;s de faire face &agrave; des mesures strictes concernant les sorties, auxquelles les autres personnes hors des centres étaient indemnis&eacute;es. Le gouvernement du Qu&eacute;bec a tenté de rem&eacute;dier &agrave; la situation en clarifiant que ces mesures ne s'appliquaient pas aux a&icirc;n&eacute;s en bonne sant&eacute; <a class="reference-link" href="https://www.ledevoir.com/societe/578307/la-revolte-des-aines?utm_medium=Social&amp;utm_campaign=Autopost&amp;utm_source=Facebook#Echobox=1588654595">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>La Commission des droits de la personne et des droits de la jeunesse du Qu&eacute;bec{{'\xa0'}} a dénoncé les contraventions donn&eacute;es &agrave; des jeunes en situation d'itin&eacute;rance et l'impact discriminatoire de l'interdiction de rassemblement sur les personnes en situation d'itin&eacute;rance <a class="reference-link" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?idArticle=2804150115">Réf{{'\xa0'}}&#x1f855;</a>. La Commission souligne que la discrimination et l'exclusion en ce temps de crise a augmenté et qu'il faut donc &eacute;viter tout profilage discriminatoire <a class="reference-link" href="http://www.fil-information.gouv.qc.ca/Pages/Article.aspx?idArticle=2804150115">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Quels sont les soutiens apportés aux communautés vulnérables en milieu urbain{{'\xa0'}}?</h3>
			<p>Les itin&eacute;rants, une des communaut&eacute;s des plus vuln&eacute;rables face &agrave; la COVID-19 ont re&ccedil;u de l&rsquo;aide de la part de la Ville de Montr&eacute;al et de ses partenaires dont Architecture sans fronti&egrave;res Qu&eacute;bec (ASFQ) <a class="reference-link" href="https://www.asf-quebec.org/appel-a-benevoles-amenagements-durgence-covid19/">Réf{{'\xa0'}}&#x1f855;</a>. Pour r&eacute;pondre &agrave; leurs besoins primaires, des centres de jour, des haltes-répit et des lieux d’hébergement d’urgence pour sans-abris ont &eacute;t&eacute; mis en place <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32519&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a> <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32581">Réf{{'\xa0'}}&#x1f855;</a>. De plus, l'Association canadienne des libert&eacute;s civiles (ACLC) vient en aide aux itin&eacute;rants ayant re&ccedil;u des contraventions pour infractions r&eacute;cr&eacute;atives municipales et souligne que celles-ci ne sont pas n&eacute;cessairement fond&eacute;es <a class="reference-link" href="https://www.lapresse.ca/covid-19/202004/19/01-5270027-covid-19-lamnistie-sera-reclamee-pour-les-contraventions.php">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Dans les quartiers les plus vuln&eacute;rables de Montr&eacute;al, la Ville de Montr&eacute;al subissant pr&eacute;alablement une crise du logement a mis en place des mesures dans l&rsquo;arrondissement Villeray-Saint-Michel-Parc-Extension <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32621&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>{{'\xa0'}} et dans le Sud-Ouest <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32480&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a> pour limiter les &eacute;victions de locataires. De plus, pour venir directement en aide au quartier de Montr&eacute;al-Nord, la Ville de Montr&eacute;al a distribué gratuitement des masques de protection, du liquide d&eacute;sinfectant et des visi&egrave;res de protection <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32646&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>. En partenariat avec la Soci&eacute;t&eacute; des Transports de Montr&eacute;al (STM), la Ville de Montr&eacute;al a fait circuler une clinique mobile de d&eacute;pistage de la COVID-19 dans Montr&eacute;al-Nord <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-05-12/montreal-nord-un-beau-decor">Réf{{'\xa0'}}&#x1f855;</a> et dans l&rsquo;arrondissement Mercier&ndash;Hochelaga-Maisonneuve <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32658">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En milieu urbain, la vuln&eacute;rabilit&eacute; touche aussi les enfants de familles plus d&eacute;favoris&eacute;es, dans ce cas l&rsquo;&eacute;cole joue souvent un r&ocirc;le important pour l&rsquo;acc&egrave;s &agrave; de la nourriture et &agrave; l&rsquo;&eacute;ducation. Le gouvernement qu&eacute;b&eacute;cois a proposé d&rsquo;offrir &agrave; ces enfants de la nourriture pour &eacute;viter les carences et une p&eacute;dagogie importante pour ne pas engendrer des retards &eacute;ducationnels <a class="reference-link" href="https://www.ledevoir.com/societe/577984/aux-confins-des-inegalites">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Comment la Ville de Montréal assure-t-elle la communication de ses initiatives auprès des citoyens et communautés défavorisés{{'\xa0'}}?</h3>
			<p>Les itin&eacute;rants ne comprennaient pas l'ampleur de la crise. En effet, bien que les travailleurs sociaux de Montr&eacute;al aient distribu&eacute; des brochures aux itin&eacute;rants, certains ne savent pas lire et d'autres ne parlent ni fran&ccedil;ais ni anglais. La communication aupr&egrave;s de cette communaut&eacute; vuln&eacute;rable était des plus difficiles <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1693445/coronavirus-itinerants-sans-abri-montreal-covid-injections-supervisees">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>La Ville de Montr&eacute;al, en plus de faire des communiqu&eacute;s de presse en ligne, a appellé personnellement les personnes &acirc;g&eacute;es ne vivant pas dans des r&eacute;sidences de personnes &acirc;g&eacute;es. Elle a aussi d&eacute;ployé une nouvelle campagne d'affiches dans les lieux les plus achaland&eacute;s de Montr&eacute;al-Nord <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32602">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>En ce qui a trait la communaut&eacute; allophone qu&eacute;b&eacute;coise, le gouvernement qu&eacute;b&eacute;cois a partagé les consignes en 19 langues et a travaill&eacute; avec plus de 80 m&eacute;dias des communaut&eacute;s culturelles <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1698270/coronavirus-cas-montreal-nord-quebec-covid-tests">Réf{{'\xa0'}}&#x1f855;</a>. Similairement, la Ville de Montr&eacute;al, entre autres dans C&ocirc;te-des-Neiges <a class="reference-link" href="https://ici.radio-canada.ca/nouvelle/1696789/montreal-cote-neiges-messages-langues-coronavirus">Réf{{'\xa0'}}&#x1f855;</a>{{'\xa0'}} et Parc-Extension <a class="reference-link" href="https://www.ledevoir.com/politique/montreal/578424/inquietude-dans-parc-extension">Réf{{'\xa0'}}&#x1f855;</a> , a informé ses citoyens n&rsquo;ayant ni acc&egrave;s{{'\xa0'}} &agrave; l'Internet ni &agrave; la t&eacute;l&eacute;vision, par un camion roulant dans les rues avec un message des nouvelles en 12 (C&ocirc;te-des-Neiges) et 10 (Parc-Extension) diff&eacute;rentes langues respectivement.</p>
			<p>Cependant, il a &eacute;t&eacute; soulev&eacute; chez les communaut&eacute;s des arrondissements de Mercier&ndash;Hochelaga-Maisonneuve et de Montr&eacute;al-Nord que la Ville de Montr&eacute;al ne diffusait pas efficacement les d&eacute;placements de sa clinique mobile chez la population vis&eacute;e <a class="reference-link" href="https://www.lapresse.ca/covid-19/202005/12/01-5273173-montreal-nord-un-beau-decor.php">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			
			<h2>R&eacute;silience / <br/><em>confinement</em></h2>

			<h3>Y a-t-il des attitudes r&eacute;silientes de la part des citoyens montr&eacute;alais envers leur cadre de vie, les espaces publics{{'\xa0'}}? Si oui, lesquelles{{'\xa0'}}?</h3>
			<p>Au printemps, &agrave; l&rsquo;Ouest de Montr&eacute;al, l&rsquo;arrondissement Pierrefonds-Roxboro est souvent victime des inondations saisonni&egrave;res. De concert avec les autorit&eacute;s locales, les citoyens ont agi avec r&eacute;silience et pr&eacute;vention en distribuant des sacs de sable aux r&eacute;sidents susceptibles d&rsquo;&ecirc;tre impact&eacute;s par la crue des eaux, en mettant en place des barrages et des pompes d&rsquo;&eacute;gout ext&eacute;rieures afin de pr&eacute;server leur maison en cette p&eacute;riode de crise <a class="reference-link" href="https://montrealgazette.com/news/local-news/west-island-gazette/west-island-officials-and-homeowners-brace-for-spring-floods/">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>&Agrave; Montr&eacute;al, les citoyens se sont intéressés davantage à la pratique du jardinage et de l&rsquo;agriculture urbaine <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/577752/la-pandemie-terreau-fertile-pour-les-apprentis-jardiniers">Réf{{'\xa0'}}&#x1f855;</a>, il s&rsquo;agit aussi d&rsquo;une mani&egrave;re r&eacute;siliente d&rsquo;assurer sa s&eacute;curit&eacute; alimentaire <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32604">Réf{{'\xa0'}}&#x1f855;</a>. La pratique du v&eacute;lo et de la marche a repr&eacute;senté une action r&eacute;siliente face &agrave; la crise, car elle a permis aux gens de se d&eacute;placer de mani&egrave;re distanc&eacute;e et &eacute;cologique, ainsi les citoyens ont demandé plus d&rsquo;espace pour circuler <a class="reference-link" href="https://plus.lapresse.ca/screens/b1b9d8a3-153b-4298-b75e-ff1074ad6327__7C___0.html?utm_medium=email&amp;utm_campaign=internal+share&amp;utm_content=screen">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<h3>Est-ce que la Ville de Montréal agit de manière résiliente face à la crise{{'\xa0'}}?</h3>
			<p>La Ville de Montr&eacute;al a fait preuve de r&eacute;silience en pi&eacute;tonnisant de nombreuses art&egrave;res commerciales dans ses arrondissements pour permettre aux citoyens de respecter les mesures sanitaires tout en encourageant l&rsquo;&eacute;conomie et les commer&ccedil;ants locaux <a class="reference-link" href="https://www.lapresse.ca/covid-19/2020-05-13/le-plan-estival-d-amenagement-urbain-de-montreal-devoile-vendredi">Réf{{'\xa0'}}&#x1f855;</a>. De plus, le <a class="reference-link" href="https://csc.maps.arcgis.com/apps/webappviewer/index.html?id=574ba931baa34f40a77a6b6181e1821f&amp;extent=-8279149.0754%2C5669447.1423%2C-8132389.9811%2C5743514.6227%2C102100"><i>Plan estival de la Ville de Montr&eacute;al</i></a> a utilisé l&rsquo;urbanisme tactique pour exploiter rapidement de nouvelles id&eacute;es pour la ville <a class="reference-link" href="https://www.ledevoir.com/societe/transports-urbanisme/578683/place-aux-velos">Réf{{'\xa0'}}&#x1f855;</a> puis s&rsquo;ajuster ce qui d&eacute;montre une certaine agilit&eacute; et flexibilit&eacute;.</p>
			<p>Montr&eacute;al a aussi fait preuve de r&eacute;silience sur le plan social en ce temps de crise en mettant en place un syst&egrave;me &eacute;labor&eacute; pour venir en aide aux itin&eacute;rants <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32519&amp;ret=http://ville.montreal.qc.ca/pls/portal/url/page/prt_vdm_fr/rep_annonces_ville/rep_communiques/communiques">Réf{{'\xa0'}}&#x1f855;</a>.{{'\xa0'}} Entre autres, elle a offert des lieux d&rsquo;h&eacute;bergement d&rsquo;urgence, des haltes-r&eacute;pits et des refuges dans des b&acirc;timents publics et espaces ext&eacute;rieurs publics depuis le d&eacute;but de la crise <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32581">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Tout de même, du côté environnemental, la résilience a été moins présente. En effet, le chroniqueur François Cardinal dénonce que le <i>Plan de relance économique du Québec</i> post-crise sanitaire n’a pas inclus le ministre de l’Environnement, ni le ministre de l’Énergie. Ainsi, certains doutes sont soulev&eacute;s face aux mesures &eacute;conomiques r&eacute;silientes post-crises qui pourraient combattre les changements climatiques <a class="reference-link" href="https://plus.lapresse.ca/screens/9a5bd941-ce1d-429b-9ea9-45d70d929ee0__7C___0.html">Réf{{'\xa0'}}&#x1f855;</a>.</p>
			<p>Dans Montr&eacute;al-Nord, un des secteurs les plus touch&eacute;s par la COVID-19 et des plus appauvris de Montr&eacute;al,{{'\xa0'}} les citoyens avec l&rsquo;aide du gouvernement ont agi avec r&eacute;silience en distribuant gratuitement 20{{'\xa0'}}800 masques <a class="reference-link" href="http://ville.montreal.qc.ca/portal/page?_pageid=5798,42657625&amp;_dad=portal&amp;_schema=PORTAL&amp;id=32614">Réf{{'\xa0'}}&#x1f855;</a>.</p>

			<ChapterNav :previous="true" :next="true" />
		</div>
	</div>
	</div>
	</div>
</template>

<script>
// @ is an alias to /src
import ChapterNav from '@/components/ChapterNav'

export default {
	name: 'Questionnements',
	components: {
		ChapterNav
	},
	activated() {
		this.$vuebar.refreshScrollbar(this.$refs.vbar)
	}
}
</script>

<style scoped>
#questionnements {
	width: 100%;
	height: 100%;
	padding: 0px;
	margin: 0px;
}
</style>